import { join } from 'node:path';

const header =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';

// Extend the upstream view manager rather than patching dependencies or replacing
// its lifecycle, accessibility, file chooser, and React Native event handling.
const android = `${header}package expo.modules.absoluteembeddedassets

import android.content.Context
import android.graphics.Bitmap
import android.net.Uri
import android.util.Log
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import androidx.webkit.WebViewAssetLoader
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature
import androidx.webkit.ScriptHandler
import androidx.webkit.WebMessageCompat
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.uimanager.ThemedReactContext
import com.facebook.react.uimanager.ViewManager
import com.reactnativecommunity.webview.RNCWebViewClient
import com.reactnativecommunity.webview.RNCWebViewManager
import com.reactnativecommunity.webview.RNCWebViewWrapper
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import java.io.ByteArrayInputStream
import java.io.File
import java.util.concurrent.ConcurrentHashMap
import java.util.WeakHashMap

private const val HOST = "appassets.androidplatform.net"
private const val PREFIX = "/absolutejs/"

internal object AbsoluteEmbeddedAssets {
  private val bundles = ConcurrentHashMap<String, Map<String, File>>()

  fun register(context: Context, rootUri: String, paths: List<String>): String {
    check(WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT) &&
      WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)) {
      "Update Android System WebView to load this application."
    }
    val uri = Uri.parse(rootUri)
    require(uri.scheme == "file" && uri.authority.isNullOrEmpty() && uri.query == null && uri.fragment == null)
    val root = File(requireNotNull(uri.path)).canonicalFile
    val parent = File(context.filesDir, "absolutejs-web").canonicalFile
    require(root.parentFile == parent && root.name.matches(Regex("amexpo_[a-f0-9]{64}")))
    require(paths.isNotEmpty() && paths.size <= 100000 && paths.distinct().size == paths.size)
    val files = paths.associateWith { path ->
      require(path.isNotEmpty() && !path.contains('\\\\') && !path.contains('%') &&
        !path.contains('?') && !path.contains('#') && path.indexOf(0.toChar()) < 0 &&
        path.split('/').all { it.isNotEmpty() && it != "." && it != ".." })
      val file = File(root, path).canonicalFile
      require(file.path.startsWith(root.path + File.separator) && file.isFile)
      file
    }
    require(files.containsKey("index.html") && files.containsKey("absolute-mobile-manifest.json"))
    bundles[root.name] = files
    Log.i("AbsoluteJS", "Expo embedded web phase: asset-host-registered")
    return "https://" + HOST + PREFIX + root.name + "/index.html"
  }

  private fun empty(status: Int, reason: String) = WebResourceResponse(
    "text/plain", "UTF-8", status, reason,
    mapOf("Cache-Control" to "no-store", "X-Content-Type-Options" to "nosniff"),
    ByteArrayInputStream(ByteArray(0))
  )

  private fun resource(path: String): WebResourceResponse {
    val bundle = path.substringBefore('/')
    val name = path.substringAfter('/', "")
    val file = bundles[bundle]?.get(name) ?: return empty(404, "Not Found")
    // Recheck canonical location at read time. Never follow a replaced symlink.
    if (file.canonicalFile != file || !file.isFile) return empty(404, "Not Found")
    val mime = when (file.extension.lowercase()) {
      "html", "htm" -> "text/html"
      "js", "mjs" -> "text/javascript"
      "json", "map" -> "application/json"
      "css" -> "text/css"
      "svg" -> "image/svg+xml"
      "wasm" -> "application/wasm"
      else -> android.webkit.MimeTypeMap.getSingleton().getMimeTypeFromExtension(file.extension.lowercase()) ?: "application/octet-stream"
    }
    return try {
      WebResourceResponse(mime, "UTF-8", 200, "OK",
        mapOf("Cache-Control" to "no-store", "X-Content-Type-Options" to "nosniff"), file.inputStream())
    } catch (_: Exception) { empty(404, "Not Found") }
  }

  private val loader = WebViewAssetLoader.Builder()
    .setDomain(HOST).setHttpAllowed(false)
    .addPathHandler(PREFIX) { path -> resource(path) }.build()

  fun intercept(request: WebResourceRequest, activeBundle: String?): WebResourceResponse? {
    val uri = request.url
    if (uri.host != HOST) return null
    if (uri.path.orEmpty().endsWith("/index.html")) Log.i("AbsoluteJS", "Expo embedded web phase: document-request")
    if (uri.path.orEmpty().endsWith("/absolute-mobile-bootstrap.js")) Log.i("AbsoluteJS", "Expo embedded web phase: bootstrap-request")
    // A reserved asset host must never fall through to DNS/network, even for
    // unknown bundles, wrong ports/schemes, methods, or malformed paths.
    if (uri.scheme != "https" || uri.port != -1 || uri.userInfo != null ||
      request.method != "GET") return empty(403, "Forbidden")
    // Root-relative image/font/CSS URLs retain their web meaning. Scope them
    // to this WebView's bundle, not the last bundle registered by another view.
    if (!uri.path.orEmpty().startsWith(PREFIX)) {
      if (request.isForMainFrame || activeBundle == null) return empty(404, "Not Found")
      return resource(activeBundle + "/" + uri.path.orEmpty().removePrefix("/"))
    }
    return loader.shouldInterceptRequest(uri) ?: empty(404, "Not Found")
  }
}

class AbsoluteEmbeddedAssetsModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("AbsoluteEmbeddedAssets")
    AsyncFunction("registerBundle") { root: String, paths: List<String> ->
      AbsoluteEmbeddedAssets.register(requireNotNull(appContext.reactContext), root, paths)
    }
  }
}

class AbsoluteEmbeddedWebViewManager : RNCWebViewManager() {
  private val scripts = WeakHashMap<RNCWebViewWrapper, ScriptHandler>()
  override fun getName() = "AbsoluteEmbeddedWebView"
  override fun setNewSource(view: RNCWebViewWrapper, value: ReadableMap?) {
    Log.i("AbsoluteJS", "Expo embedded web phase: source-assigned")
    super.setNewSource(view, value)
  }
  override fun setMessagingEnabled(view: RNCWebViewWrapper, value: Boolean) {
    super.setMessagingEnabled(view, value)
    // Upstream reports sourceOrigin as event.url and accepts subframe messages.
    // Retain its event dispatch, but bind this bridge to our main-frame origin
    // and attach the native-observed document URL, never a JS-supplied URL.
    if (!WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)) return
    WebViewCompat.removeWebMessageListener(view.webView, "ReactNativeWebView")
    if (!value) return
    WebViewCompat.addWebMessageListener(view.webView, "ReactNativeWebView", setOf("https://" + HOST)) {
        webView, message, sourceOrigin, isMainFrame, _ ->
      if (isMainFrame && sourceOrigin.scheme == "https" && sourceOrigin.host == HOST &&
          message.type == WebMessageCompat.TYPE_STRING) {
        val url = webView.url
        val data = message.data
        if (url != null && data != null) view.webView.onMessage(data, url)
      }
    }
  }
  override fun setInjectedJavaScriptBeforeContentLoaded(view: RNCWebViewWrapper, value: String?) {
    scripts.remove(view)?.remove()
    if (value == null) return
    // onPageStarted injection races module execution on Android. Register with
    // Chromium before navigation, scoped to our virtual asset origin only.
    check(WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)) {
      "AbsoluteJS requires an Android System WebView with document-start script support."
    }
    scripts[view] = WebViewCompat.addDocumentStartJavaScript(view.webView, value, setOf("https://" + HOST))
  }
  override fun onDropViewInstance(view: RNCWebViewWrapper) {
    scripts.remove(view)?.remove()
    if (WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER))
      WebViewCompat.removeWebMessageListener(view.webView, "ReactNativeWebView")
    super.onDropViewInstance(view)
  }
  override fun addEventEmitters(context: ThemedReactContext, view: RNCWebViewWrapper) {
    Log.i("AbsoluteJS", "Expo embedded web phase: asset-host-view-created")
    view.webView.webViewClient = object : RNCWebViewClient() {
      @Volatile private var activeBundle: String? = null
      override fun onPageStarted(view: WebView, url: String, favicon: Bitmap?) {
        Log.i("AbsoluteJS", "Expo embedded web phase: document-started")
        val uri = Uri.parse(url)
        activeBundle = if (uri.scheme == "https" && uri.host == HOST && uri.path.orEmpty().startsWith(PREFIX))
          uri.path!!.removePrefix(PREFIX).substringBefore('/') else null
        super.onPageStarted(view, url, favicon)
      }
      override fun shouldInterceptRequest(view: WebView, request: WebResourceRequest): WebResourceResponse? =
        AbsoluteEmbeddedAssets.intercept(request, activeBundle) ?: super.shouldInterceptRequest(view, request)
    }
  }
}

class AbsoluteEmbeddedWebViewPackage : ReactPackage {
  override fun createNativeModules(context: ReactApplicationContext): List<NativeModule> = emptyList()
  override fun createViewManagers(context: ReactApplicationContext): List<ViewManager<*, *>> = listOf(AbsoluteEmbeddedWebViewManager())
}
`;

const plugin = `${header}const { withMainApplication } = require('expo/config-plugins');
module.exports = config => withMainApplication(config, value => {
  if (value.modResults.language !== 'kt') throw new Error('AbsoluteJS embedded assets require the managed Kotlin application.');
  const name = 'expo.modules.absoluteembeddedassets.AbsoluteEmbeddedWebViewPackage';
  const registration = 'add(' + name + '())';
  const source = value.modResults.contents;
  if (!source.includes(registration)) {
    const anchor = 'PackageList(this).packages.apply {';
    if (source.split(anchor).length !== 2) throw new Error('Cannot safely register AbsoluteJS embedded WebView in MainApplication.');
    value.modResults.contents = source.replace(anchor, anchor + '\\n              ' + registration);
  }
  return value;
});
`;

const runtime = `${header}import { requireNativeModule } from 'expo-modules-core';
import { Platform, requireNativeComponent } from 'react-native';

export const absoluteEmbeddedNativeConfig = Platform.OS === 'android'
  ? { component: requireNativeComponent('AbsoluteEmbeddedWebView') }
  : undefined;

export const registerAbsoluteEmbeddedBundle = async (rootUri: string, paths: string[], indexUri: string): Promise<string> => {
  if (Platform.OS !== 'android') return indexUri;
  const native = requireNativeModule<{ registerBundle(root: string, paths: string[]): Promise<string> }>('AbsoluteEmbeddedAssets');
  return native.registerBundle(rootUri, paths);
};
`;

export const absoluteExpoEmbeddedAssetsFiles = (project: string) => {
	const root = join(project, 'modules/absolute-embedded-assets');

	return new Map([
		[
			join(root, 'expo-module.config.json'),
			`${JSON.stringify(
				{
					android: {
						modules: [
							'expo.modules.absoluteembeddedassets.AbsoluteEmbeddedAssetsModule'
						]
					},
					platforms: ['android']
				},
				null,
				2
			)}\n`
		],
		[
			join(root, 'android/build.gradle'),
			`${header}plugins { id 'com.android.library'; id 'expo-module-gradle-plugin' }
group = 'expo.modules.absoluteembeddedassets'
version = '0.0.1'
android {
  namespace 'expo.modules.absoluteembeddedassets'
  defaultConfig { versionCode 1; versionName '0.0.1' }
}
dependencies {
  implementation 'com.facebook.react:react-android'
  implementation project(':react-native-webview')
  implementation 'androidx.webkit:webkit:1.14.0'
}
`
		],
		[
			join(root, 'android/src/main/AndroidManifest.xml'),
			'<manifest xmlns:android="http://schemas.android.com/apk/res/android" />\n'
		],
		[
			join(
				root,
				'android/src/main/java/expo/modules/absoluteembeddedassets/AbsoluteEmbeddedAssetsModule.kt'
			),
			android
		],
		[join(project, 'plugins/withAbsoluteEmbeddedAssets.js'), plugin],
		[join(project, 'src/generated/AbsoluteEmbeddedAssets.ts'), runtime]
	]);
};
