import { join } from 'node:path';

const HEADER =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';
const XML_HEADER =
	'<!-- Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync. -->\n';

const moduleConfig = `${JSON.stringify(
	{
		android: {
			modules: [
				'expo.modules.absoluteactivityresultrecovery.AbsoluteActivityResultRecoveryModule'
			]
		},
		apple: { modules: ['AbsoluteActivityResultRecoveryModule'] },
		platforms: ['apple', 'android']
	},
	null,
	2
)}
`;

const podspec = `${HEADER}Pod::Spec.new do |s|
  s.name = 'AbsoluteActivityResultRecovery'
  s.version = '0.0.1'
  s.summary = 'AbsoluteJS native runtime readiness bridge'
  s.description = 'Generated lifecycle and embedded-content readiness bridge for an AbsoluteJS Expo application.'
  s.author = 'AbsoluteJS'
  s.homepage = 'https://absolutejs.com'
  s.platforms = { :ios => '16.4' }
  s.source = { git: '' }
  s.static_framework = true
  s.dependency 'ExpoModulesCore'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.source_files = '**/*.{h,m,mm,swift,hpp,cpp}'
end
`;

const iosModule = `${HEADER}import ExpoModulesCore

public final class AbsoluteActivityResultRecoveryModule: Module {
  public func definition() -> ModuleDefinition {
    Name("AbsoluteActivityResultRecovery")

    Function("markApplicationRuntimeReady") { }

    Function("markEmbeddedWebReady") {
		let info = Bundle.main.infoDictionary ?? [:]
		let version = info["CFBundleShortVersionString"] as? String ?? "unknown"
		let build = info["CFBundleVersion"] as? String ?? "unknown"
		NSLog("AbsoluteJS: Expo embedded web content ready; version=%@; build=%@", version, build)
    }

    Function("markEmbeddedWebPhase") { (phase: String) in
      let allowed = [
        "assets-start", "assets-ready", "assets-root-failed",
        "assets-directory-failed", "assets-destination-failed",
        "assets-module-failed", "assets-source-failed",
        "assets-download-failed", "assets-copy-failed",
        "assets-read-failed", "assets-write-failed",
        "assets-finalize-failed", "assets-unexpected-failed",
        "devices-start", "devices-ready", "devices-failed"
      ]
      if allowed.contains(phase) {
        NSLog("AbsoluteJS: Expo embedded web phase: %@", phase)
      }
    }

    Function("takePendingCancellation") { false }
  }
}
`;

const androidBuild = `${HEADER}plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.absoluteactivityresultrecovery'
version = '0.0.1'

android {
  namespace 'expo.modules.absoluteactivityresultrecovery'
  defaultConfig {
    versionCode 1
    versionName '0.0.1'
  }
  lintOptions { abortOnError false }
}
`;

const androidManifest = `${XML_HEADER}<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
`;

const androidModule = `${HEADER}package expo.modules.absoluteactivityresultrecovery

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.provider.MediaStore
import android.util.Log
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition

data class AbsolutePendingActivityResult(
  val requestCode: Int,
  val resultCode: Int,
  val data: Intent?
)

object AbsoluteActivityResultRecoveryState {
  @Volatile
  var applicationRuntimeReady = false

  private val pendingActivityResults = ArrayDeque<AbsolutePendingActivityResult>()
  private var pendingCancellations = 0

  private const val preferencesName = "absolutejs.activity-result-recovery"
  private const val pickerRequestCodeKey = "picker-request-code"

  @Synchronized
  fun registerPickerRequest(context: Context, requestCode: Int, intent: Intent) {
    val action = intent.action
    val isPicker = action == MediaStore.ACTION_IMAGE_CAPTURE ||
      action == MediaStore.ACTION_VIDEO_CAPTURE ||
      action == MediaStore.ACTION_PICK_IMAGES ||
      action == Intent.ACTION_PICK ||
      action == Intent.ACTION_GET_CONTENT ||
      action == Intent.ACTION_OPEN_DOCUMENT ||
      action?.endsWith(".PICK") == true ||
      intent.type?.startsWith("image/") == true ||
      intent.hasExtra(MediaStore.EXTRA_OUTPUT)
    if (!isPicker) return
    context.getSharedPreferences(preferencesName, Context.MODE_PRIVATE)
      .edit()
      .putInt(pickerRequestCodeKey, requestCode)
      .apply()
  }

  @Synchronized
  fun consumePickerCancellation(context: Context, requestCode: Int, resultCode: Int): Boolean {
	val preferences = context.getSharedPreferences(preferencesName, Context.MODE_PRIVATE)
	val pickerRequestCode = preferences.getInt(pickerRequestCodeKey, Int.MIN_VALUE)
	if (pickerRequestCode != requestCode) return false
	preferences.edit().remove(pickerRequestCodeKey).apply()
	return resultCode == Activity.RESULT_CANCELED
  }

  @Synchronized
  fun enqueueActivityResult(requestCode: Int, resultCode: Int, data: Intent?, pickerCancelled: Boolean) {
    if (pendingActivityResults.size == 8) pendingActivityResults.removeFirst()
    pendingActivityResults.addLast(
      AbsolutePendingActivityResult(requestCode, resultCode, data?.let(::Intent))
    )
	if (pickerCancelled && pendingCancellations < 8) {
	  pendingCancellations += 1
	}
	Log.d("AbsoluteJS", "Queued early Android activity result; pending=" + pendingActivityResults.size)
  }

  @Synchronized
  fun takePendingCancellation(): Boolean {
    if (pendingCancellations == 0) return false
    pendingCancellations -= 1
	return true
  }

  @Synchronized
  fun hasPendingActivityResults() = pendingActivityResults.isNotEmpty()

  @Synchronized
  fun drainActivityResults(): List<AbsolutePendingActivityResult> {
    val drained = pendingActivityResults.toList()
    pendingActivityResults.clear()
	Log.d("AbsoluteJS", "Replaying queued Android activity results; count=" + drained.size)
    return drained
  }
}

class AbsoluteActivityResultRecoveryModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("AbsoluteActivityResultRecovery")

    Function("markApplicationRuntimeReady") {
      AbsoluteActivityResultRecoveryState.applicationRuntimeReady = true
	  Log.d("AbsoluteJS", "Expo application runtime ready for Android activity results")
    }

    Function("markEmbeddedWebReady") {
	  Log.i("AbsoluteJS", "Expo embedded web content ready")
    }

    Function("markEmbeddedWebPhase") { phase: String ->
	  val allowed = setOf("assets-start", "assets-ready", "assets-root-failed", "assets-directory-failed", "assets-destination-failed", "assets-module-failed", "assets-source-failed", "assets-download-failed", "assets-copy-failed", "assets-read-failed", "assets-write-failed", "assets-finalize-failed", "assets-unexpected-failed", "devices-start", "devices-ready", "devices-failed")
	  if (allowed.contains(phase)) Log.i("AbsoluteJS", "Expo embedded web phase: " + phase)
    }

	Function("takePendingCancellation") {
	  AbsoluteActivityResultRecoveryState.takePendingCancellation()
	}
  }
}
`;

const runtime = `${HEADER}import { requireNativeModule } from 'expo-modules-core';

type AbsoluteActivityResultRecoveryNative = {
	markApplicationRuntimeReady(): void;
	markEmbeddedWebPhase(phase: AbsoluteEmbeddedWebPhase): void;
	markEmbeddedWebReady(): void;
	takePendingCancellation(): boolean;
};

const native = requireNativeModule<AbsoluteActivityResultRecoveryNative>(
	'AbsoluteActivityResultRecovery'
);

export const markAbsoluteApplicationRuntimeReady = () =>
	native.markApplicationRuntimeReady();

export const markAbsoluteEmbeddedWebReady = () =>
	native.markEmbeddedWebReady();

export type AbsoluteEmbeddedWebPhase =
	| 'assets-start'
	| 'assets-ready'
	| 'assets-root-failed'
	| 'assets-directory-failed'
	| 'assets-destination-failed'
	| 'assets-module-failed'
	| 'assets-source-failed'
	| 'assets-download-failed'
	| 'assets-copy-failed'
	| 'assets-read-failed'
	| 'assets-write-failed'
	| 'assets-finalize-failed'
	| 'assets-unexpected-failed'
	| 'devices-start'
	| 'devices-ready'
	| 'devices-failed';

export const markAbsoluteEmbeddedWebPhase = (phase: AbsoluteEmbeddedWebPhase) =>
	native.markEmbeddedWebPhase(phase);

export const takeAbsoluteActivityResultCancellation = () =>
	native.takePendingCancellation();
`;

export const absoluteExpoActivityResultRecoveryFiles = (project: string) =>
	new Map<string, string>([
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/expo-module.config.json'
			),
			moduleConfig
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/ios/AbsoluteActivityResultRecovery.podspec'
			),
			podspec
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/ios/AbsoluteActivityResultRecoveryModule.swift'
			),
			iosModule
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/build.gradle'
			),
			androidBuild
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/src/main/AndroidManifest.xml'
			),
			androidManifest
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/src/main/java/expo/modules/absoluteactivityresultrecovery/AbsoluteActivityResultRecoveryModule.kt'
			),
			androidModule
		],
		[
			join(project, 'src/generated/AbsoluteActivityResultRecovery.ts'),
			runtime
		]
	]);
