import { join } from 'node:path';

const HEADER =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';
const XML_HEADER =
	'<!-- Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync. -->\n';

const moduleConfig = `${JSON.stringify(
	{
		android: {
			modules: [
				'expo.modules.absoluteactivityresultrecovery.AbsoluteActivityResultRecoveryModule'
			]
		},
		platforms: ['android']
	},
	null,
	2
)}
`;

const androidBuild = `${HEADER}plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.absoluteactivityresultrecovery'
version = '0.0.1'

android {
  namespace 'expo.modules.absoluteactivityresultrecovery'
  defaultConfig {
    versionCode 1
    versionName '0.0.1'
  }
  lintOptions { abortOnError false }
}
`;

const androidManifest = `${XML_HEADER}<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
`;

const androidModule = `${HEADER}package expo.modules.absoluteactivityresultrecovery

import android.content.Intent
import android.util.Log
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition

data class AbsolutePendingActivityResult(
  val requestCode: Int,
  val resultCode: Int,
  val data: Intent?
)

object AbsoluteActivityResultRecoveryState {
  @Volatile
  var applicationRuntimeReady = false

  private val pendingActivityResults = ArrayDeque<AbsolutePendingActivityResult>()

  @Synchronized
  fun enqueueActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    if (pendingActivityResults.size == 8) pendingActivityResults.removeFirst()
    pendingActivityResults.addLast(
      AbsolutePendingActivityResult(requestCode, resultCode, data?.let(::Intent))
    )
	Log.d("AbsoluteJS", "Queued early Android activity result; pending=" + pendingActivityResults.size)
  }

  @Synchronized
  fun hasPendingActivityResults() = pendingActivityResults.isNotEmpty()

  @Synchronized
  fun drainActivityResults(): List<AbsolutePendingActivityResult> {
    val drained = pendingActivityResults.toList()
    pendingActivityResults.clear()
	Log.d("AbsoluteJS", "Replaying queued Android activity results; count=" + drained.size)
    return drained
  }
}

class AbsoluteActivityResultRecoveryModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("AbsoluteActivityResultRecovery")

    Function("markApplicationRuntimeReady") {
      AbsoluteActivityResultRecoveryState.applicationRuntimeReady = true
	  Log.d("AbsoluteJS", "Expo application runtime ready for Android activity results")
    }
  }
}
`;

const runtime = `${HEADER}import { requireNativeModule } from 'expo-modules-core';

type AbsoluteActivityResultRecoveryNative = {
	markApplicationRuntimeReady(): void;
};

const native = requireNativeModule<AbsoluteActivityResultRecoveryNative>(
	'AbsoluteActivityResultRecovery'
);

export const markAbsoluteApplicationRuntimeReady = () =>
	native.markApplicationRuntimeReady();
`;

export const absoluteExpoActivityResultRecoveryFiles = (project: string) =>
	new Map<string, string>([
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/expo-module.config.json'
			),
			moduleConfig
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/build.gradle'
			),
			androidBuild
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/src/main/AndroidManifest.xml'
			),
			androidManifest
		],
		[
			join(
				project,
				'modules/absolute-activity-result-recovery/android/src/main/java/expo/modules/absoluteactivityresultrecovery/AbsoluteActivityResultRecoveryModule.kt'
			),
			androidModule
		],
		[
			join(project, 'src/generated/AbsoluteActivityResultRecovery.ts'),
			runtime
		]
	]);
