import {
	access,
	cp,
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	rename,
	rm,
	writeFile
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import type { NormalizedAbsoluteMobileConfig } from './config';
import {
	ABSOLUTE_EXPO_AUTH_PACKAGE,
	ABSOLUTE_EXPO_AUTH_CORE_VERSION,
	ABSOLUTE_EXPO_AUTH_VERSION,
	ABSOLUTE_EXPO_SYNC_CORE_VERSION,
	ABSOLUTE_EXPO_SYNC_PACKAGE,
	ABSOLUTE_EXPO_SYNC_VERSION,
	projectUsesAbsoluteSync,
	resolveAbsoluteMobileAuthManifest,
	type AbsoluteMobileAuthManifest
} from './nativeAuth';
import { discoverAbsoluteSyncSchema } from './syncSchema';
import type { SyncLocalStoreSchemaBundle } from '@absolutejs/sync/client';
import {
	absoluteDeviceNativeRequirements,
	resolveAbsoluteDeviceCapabilityPlan,
	type AbsoluteDeviceCapabilityPlan
} from './deviceCapabilities';

const EXPO_GENERATED_HEADER =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';
const EXPO_ASSET_EXTENSION = '.absasset';
const EXPO_PROJECT_MARKER = '.absolutejs-expo-project';

type AbsoluteExpoNativeDataManifest = {
	appBuild: string;
	pages: {
		bundleHash: string;
		contract: string;
		pageId: string;
	}[];
	productionOrigin: string;
	routes: { method: 'GET'; pageId: string; pattern: string }[];
	runtime: string;
};

type AbsoluteExpoAssetEntry = { asset: string; path: string };

export type WriteAbsoluteExpoProjectOptions = {
	force?: boolean;
	projectRoot: string;
};

const exists = async (path: string) => {
	try {
		await access(path);

		return true;
	} catch {
		return false;
	}
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === 'object' && value !== null && !Array.isArray(value);

const requireManifestString = (value: unknown, field: string) => {
	if (typeof value !== 'string' || !value) {
		throw new TypeError(`AbsoluteJS mobile manifest ${field} is invalid.`);
	}

	return value;
};

const expoNativeDataManifest = (
	value: unknown
): AbsoluteExpoNativeDataManifest => {
	if (
		!isRecord(value) ||
		!Array.isArray(value.pages) ||
		!Array.isArray(value.routes)
	) {
		throw new TypeError('AbsoluteJS mobile manifest is invalid.');
	}
	const pages = value.pages.map((page) => {
		if (!isRecord(page))
			throw new TypeError('AbsoluteJS mobile manifest page is invalid.');

		return {
			bundleHash: requireManifestString(
				page.bundleHash,
				'page.bundleHash'
			),
			contract: requireManifestString(page.contract, 'page.contract'),
			pageId: requireManifestString(page.pageId, 'page.pageId')
		};
	});
	const routes = value.routes.flatMap((route) => {
		if (!isRecord(route) || typeof route.method !== 'string') {
			throw new TypeError('AbsoluteJS mobile manifest route is invalid.');
		}
		if (route.method !== 'GET') return [];

		return [
			{
				method: 'GET' as const,
				pageId: requireManifestString(route.pageId, 'route.pageId'),
				pattern: requireManifestString(route.pattern, 'route.pattern')
			}
		];
	});

	return {
		appBuild: requireManifestString(value.appBuild, 'appBuild'),
		pages,
		productionOrigin: requireManifestString(
			value.productionOrigin,
			'productionOrigin'
		),
		routes,
		runtime: requireManifestString(value.runtime, 'runtime')
	};
};

const portableRelative = (from: string, destination: string) => {
	const value = relative(from, destination).replaceAll('\\', '/');

	return value.startsWith('.') ? value : `./${value}`;
};

const routeSegments = (route: string) => {
	const segments = route.split('/').filter(Boolean);

	return segments.map((segment, index) => {
		if (segment.startsWith(':')) return `[${segment.slice(1)}]`;
		if (segment === '*' && index === segments.length - 1)
			return '[...absoluteWildcard]';
		if (
			segment === '.' ||
			segment === '..' ||
			!/^[A-Za-z0-9._~-]+$/u.test(segment)
		) {
			throw new TypeError(
				`Expo native route ${route} contains an unsupported segment ${segment}.`
			);
		}

		return segment;
	});
};

const routeFile = (project: string, route: string) =>
	join(project, 'app', ...routeSegments(route), 'index.tsx');

const packageDependencies = (plan: AbsoluteDeviceCapabilityPlan) =>
	Object.fromEntries(
		plan.requiredPackages.map((spec) => {
			const separator = spec.lastIndexOf('@');

			return [spec.slice(0, separator), spec.slice(separator + 1)];
		})
	);

const expoPackage = (
	auth: boolean,
	sync: boolean,
	devices: AbsoluteDeviceCapabilityPlan
) => ({
	dependencies: {
		'@absolutejs/devices': '0.7.0',
		'@absolutejs/devices-expo': '0.0.2',
		...(auth
			? {
					'@absolutejs/auth': ABSOLUTE_EXPO_AUTH_CORE_VERSION,
					[ABSOLUTE_EXPO_AUTH_PACKAGE]: ABSOLUTE_EXPO_AUTH_VERSION
				}
			: {}),
		...(sync
			? {
					'@absolutejs/sync': ABSOLUTE_EXPO_SYNC_CORE_VERSION,
					[ABSOLUTE_EXPO_SYNC_PACKAGE]: ABSOLUTE_EXPO_SYNC_VERSION
				}
			: {}),
		expo: '~57.0.9',
		'expo-asset': '~57.0.15',
		'expo-constants': '~57.0.16',
		'expo-dev-client': '~57.0.16',
		'expo-file-system': '~57.0.6',
		'expo-haptics': '~57.0.2',
		'expo-linking': '~57.0.8',
		...(sync
			? {
					'expo-background-task': '~57.0.14',
					'expo-network': '~57.0.1',
					'expo-sqlite': '~57.0.2',
					'expo-task-manager': '~57.0.14',
					'expo-updates': '~57.0.19'
				}
			: {}),
		'expo-router': '~57.0.17',
		...(auth
			? {
					'expo-secure-store': '~57.0.2',
					'expo-web-browser': '~57.0.2'
				}
			: {}),
		react: '19.2.3',
		'react-native': '0.86.3',
		'react-native-safe-area-context': '~5.7.0',
		'react-native-screens': '4.26.0',
		'react-native-webview': '13.16.1',
		...packageDependencies(devices)
	},
	devDependencies: {
		'@types/react': '~19.2.2',
		typescript: '~6.0.3'
	},
	main: 'expo-router/entry',
	name: 'absolutejs-expo-shell',
	private: true,
	scripts: {
		android: 'expo run:android',
		ios: 'expo run:ios',
		start: 'expo start --dev-client'
	},
	version: '0.0.0'
});

const expoAppConfig = (
	config: NormalizedAbsoluteMobileConfig,
	auth: boolean,
	sync: boolean,
	devices: AbsoluteDeviceCapabilityPlan
) => {
	const requirements = absoluteDeviceNativeRequirements(devices);
	const usageKey = (purpose: string) => {
		if (purpose === 'camera') return 'NSCameraUsageDescription';
		if (purpose === 'photo-library')
			return 'NSPhotoLibraryUsageDescription';
		if (purpose === 'photo-library-add')
			return 'NSPhotoLibraryAddUsageDescription';
		if (purpose === 'location-always')
			return 'NSLocationAlwaysAndWhenInUseUsageDescription';

		return 'NSLocationWhenInUseUsageDescription';
	};
	const usageDescription = (purpose: string) => {
		if (purpose === 'camera')
			return `${config.appName} uses your camera when you choose to take a photo.`;
		if (purpose === 'photo-library')
			return `${config.appName} accesses your photo library only for photo actions you choose.`;
		if (purpose.startsWith('location-'))
			return `${config.appName} uses your location only while you use the app and request a location-based action.`;

		return `${config.appName} adds to your photo library only for photo actions you choose.`;
	};
	const descriptions = Object.fromEntries(
		requirements.iosUsageDescriptions.map((purpose) => [
			usageKey(purpose),
			usageDescription(purpose)
		])
	);
	const devicePlugins = [
		...new Set(
			devices.capabilities.flatMap(
				(name) => devices.providers[name]?.plugins ?? []
			)
		)
	];
	const configuredPlugins = devicePlugins.map((plugin) => {
		if (plugin === 'expo-image-picker')
			return [
				plugin,
				{
					cameraPermission: descriptions.NSCameraUsageDescription,
					microphonePermission: false,
					photosPermission:
						descriptions.NSPhotoLibraryUsageDescription
				}
			];
		if (plugin === 'expo-location')
			return [
				plugin,
				{
					locationWhenInUsePermission:
						descriptions.NSLocationWhenInUseUsageDescription
				}
			];

		return plugin;
	});

	return {
		expo: {
			android: {
				...(devicePlugins.includes('expo-image-picker')
					? {
							blockedPermissions: [
								'android.permission.READ_EXTERNAL_STORAGE',
								'android.permission.RECORD_AUDIO',
								'android.permission.WRITE_EXTERNAL_STORAGE'
							]
						}
					: {}),
				intentFilters: config.deepLinkHosts.map((host) => ({
					action: 'VIEW',
					autoVerify: true,
					category: ['BROWSABLE', 'DEFAULT'],
					data: [{ host, pathPrefix: '/', scheme: 'https' }]
				})),
				package: config.appId,
				permissions: requirements.androidPermissions
			},
			experiments: { typedRoutes: true },
			ios: {
				associatedDomains: config.deepLinkHosts.map(
					(host) => `applinks:${host}`
				),
				bundleIdentifier: config.appId,
				infoPlist: descriptions,
				...(requirements.iosPrivacyAccessedApis.length > 0
					? {
							privacyManifests: {
								NSPrivacyAccessedAPITypes:
									requirements.iosPrivacyAccessedApis.map(
										({ api, reasons }) => ({
											NSPrivacyAccessedAPIType: api,
											NSPrivacyAccessedAPITypeReasons:
												reasons
										})
									)
							}
						}
					: {}),
				...(config.iosVersion ? { buildNumber: config.iosVersion } : {})
			},
			name: config.appName,
			plugins: [
				'expo-router',
				['expo-dev-client', { launchMode: 'most-recent' }],
				...(auth ? ['expo-secure-store'] : []),
				...(sync
					? [
							'expo-sqlite',
							'expo-background-task',
							'expo-task-manager'
						]
					: []),
				...configuredPlugins
			],
			runtimeVersion: { policy: 'appVersion' },
			scheme: config.deepLinkScheme,
			slug: config.appId.toLowerCase().replaceAll('.', '-'),
			version: config.iosVersion ?? '0.1.0'
		}
	};
};

const expoDynamicAppConfig = `${EXPO_GENERATED_HEADER}const config = require('./app.json');

if (process.env.ABSOLUTE_EXPO_DEVELOPMENT === '1' && process.env.ABSOLUTE_EXPO_DEVELOPMENT_CA_PATH) {
	config.expo.plugins = [
		...config.expo.plugins,
		'./plugins/withAbsoluteDevelopmentCa'
	];
}

module.exports = config;
`;

const expoDevelopmentCaPlugin = `${EXPO_GENERATED_HEADER}const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const { copyFile, mkdir } = require('node:fs/promises');
const path = require('node:path');

const NETWORK_CONFIG = [
	'<?xml version="1.0" encoding="utf-8"?>',
	'<network-security-config>',
	'\t<debug-overrides>',
	'\t\t<trust-anchors>',
	'\t\t\t<certificates src="@raw/absolutejs_dev_ca" />',
	'\t\t</trust-anchors>',
	'\t</debug-overrides>',
	'</network-security-config>',
	''
].join('\\n');

const withAbsoluteDevelopmentCa = config => {
	config = withAndroidManifest(config, value => {
		const application = AndroidConfig.Manifest.getMainApplicationOrThrow(value.modResults);
		application.$['android:networkSecurityConfig'] = '@xml/absolutejs_dev_network_security';
		return value;
	});
	return withDangerousMod(config, ['android', async value => {
		const certificate = process.env.ABSOLUTE_EXPO_DEVELOPMENT_CA_PATH;
		if (!certificate) throw new Error('AbsoluteJS Expo HTTPS development requires its development CA path.');
		const resources = path.join(value.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');
		await Promise.all([
			mkdir(path.join(resources, 'raw'), { recursive: true }),
			mkdir(path.join(resources, 'xml'), { recursive: true })
		]);
		await Promise.all([
			copyFile(certificate, path.join(resources, 'raw', 'absolutejs_dev_ca.pem')),
			require('node:fs/promises').writeFile(path.join(resources, 'xml', 'absolutejs_dev_network_security.xml'), NETWORK_CONFIG)
		]);
		return value;
	}]);
};

module.exports = withAbsoluteDevelopmentCa;
`;

const metroConfig = (projectRoot: string) =>
	`${EXPO_GENERATED_HEADER}const { getDefaultConfig } = require('expo/metro-config');
const path = require('node:path');

const projectRoot = __dirname;
const appRoot = ${JSON.stringify(projectRoot)};
const config = getDefaultConfig(projectRoot);
config.resolver.assetExts.push('absasset');
config.resolver.nodeModulesPaths = [
	path.join(projectRoot, 'node_modules'),
	path.join(appRoot, 'node_modules')
];
config.watchFolders = [appRoot];

module.exports = config;
`;

const layoutSource = (auth: boolean, sync: boolean) =>
	`${EXPO_GENERATED_HEADER}import { Stack } from 'expo-router';
import '../src/generated/AbsoluteDevices';
${auth ? "import { useEffect, useState } from 'react';\nimport { startAbsoluteExpoAuth } from '../src/generated/AbsoluteAuth';" : ''}
${sync ? "import { startAbsoluteExpoSync } from '../src/generated/AbsoluteSync';" : ''}

export default function AbsoluteLayout() {
	${
		auth
			? `const [ready, setReady] = useState(false);
	useEffect(() => {
		let active = true;
		void ${sync ? 'startAbsoluteExpoSync' : 'startAbsoluteExpoAuth'}().then(() => { if (active) setReady(true); });
		return () => { active = false; };
	}, []);
	if (!ready) return null;`
			: ''
	}
	return <Stack screenOptions={{ headerShown: false }} />;
}
`;

const nativeDiagnosticSource = `${EXPO_GENERATED_HEADER}import * as Haptics from 'expo-haptics';
import { Link } from 'expo-router';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

export default function AbsoluteNativeDiagnostic() {
	return (
		<SafeAreaView style={styles.page}>
			<View style={styles.card}>
				<Text style={styles.eyebrow}>ABSOLUTEJS · EXPO EXPERIMENT</Text>
				<Text style={styles.title}>This screen is native React UI.</Text>
				<Text style={styles.body}>Ordinary AbsoluteJS routes remain embedded web routes. Only explicitly owned routes use React Native.</Text>
				<Pressable style={styles.button} onPress={() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)}>
					<Text style={styles.buttonText}>Test native haptics</Text>
				</Pressable>
				<Link href="/" style={styles.link}>Open the AbsoluteJS app</Link>
			</View>
		</SafeAreaView>
	);
}

const styles = StyleSheet.create({
	body: { color: '#cbd5e1', fontSize: 16, lineHeight: 24 },
	button: { backgroundColor: '#f8fafc', borderRadius: 12, padding: 14 },
	buttonText: { color: '#020617', fontSize: 16, fontWeight: '700', textAlign: 'center' },
	card: { backgroundColor: '#0f172a', borderRadius: 24, gap: 20, maxWidth: 560, padding: 28, width: '100%' },
	eyebrow: { color: '#38bdf8', fontSize: 12, fontWeight: '800', letterSpacing: 1.5 },
	link: { color: '#7dd3fc', fontSize: 16, textAlign: 'center' },
	page: { alignItems: 'center', backgroundColor: '#020617', flex: 1, justifyContent: 'center', padding: 20 },
	title: { color: '#f8fafc', fontSize: 32, fontWeight: '800' }
});
`;

const devicesRuntimeSource = (
	config: NormalizedAbsoluteMobileConfig,
	plan: AbsoluteDeviceCapabilityPlan,
	auth: boolean
) => {
	const imports = plan.capabilities.map((name, index) => {
		const provider = plan.providers[name];
		if (!provider)
			throw new TypeError(
				`Missing Expo device capability provider ${name}.`
			);

		return `import { ${provider.factory} as absoluteExpoCapability${index} } from ${JSON.stringify(provider.module)};`;
	});
	const pushIndex = plan.capabilities.indexOf('pushNotifications');
	const push = pushIndex !== -1;
	if (push && !auth)
		throw new TypeError(
			'Expo push notifications require the provisioned AbsoluteJS Auth runtime.'
		);
	const entries = plan.capabilities
		.map(
			(name, index) =>
				`${JSON.stringify(name)}: absoluteExpoCapability${index}(${name === 'pushNotifications' ? 'absoluteExpoPushOptions' : ''})`
		)
		.join(',\n\t');
	const pushSource = push
		? `const INSTALLATION_KEY = 'absolutejs.push.installation-id';
const requirePushResponse = async (response: Response, operation: string) => {
	if (!response.ok) throw new Error(\`AbsoluteJS native push \${operation} failed with HTTP \${response.status}.\`);
	return response.json() as Promise<Record<string, unknown>>;
};
const absoluteExpoPushOptions = {
	onRegistration: async (registration: { platform: 'apns' | 'fcm'; token: string }) => {
		const known = await absoluteExpoDevices.storage.get(INSTALLATION_KEY);
		const register = (installationId?: string | null) => absoluteExpoAuth.fetch('/auth/push', {
			body: JSON.stringify({ ...(installationId ? { installationId } : {}), platform: registration.platform, token: registration.token }),
			headers: { 'content-type': 'application/json' },
			method: 'POST'
		});
		let response = await register(known);
		const conflict = response.status === 409 && await response.clone().json().then(value => typeof value === 'object' && value !== null && Reflect.get(value, 'code') === 'installation-ownership').catch(() => false);
		if (known && conflict) {
			await absoluteExpoDevices.storage.remove(INSTALLATION_KEY);
			response = await register();
		}
		const result = await requirePushResponse(response, 'registration');
		if (typeof result.installationId !== 'string' || !result.installationId || result.installationId.length > 128) throw new Error('AbsoluteJS native push returned an invalid installation identity.');
		await absoluteExpoDevices.storage.set(INSTALLATION_KEY, result.installationId);
	},
	onUnregistration: async () => {
		const installationId = await absoluteExpoDevices.storage.get(INSTALLATION_KEY);
		if (!installationId) return;
		await requirePushResponse(await absoluteExpoAuth.fetch('/auth/push', {
			body: JSON.stringify({ installationId }),
			headers: { 'content-type': 'application/json' },
			method: 'DELETE'
		}), 'removal');
		await absoluteExpoDevices.storage.remove(INSTALLATION_KEY);
	}
};`
		: '';

	return `${EXPO_GENERATED_HEADER}import { installDeviceAdapter } from '@absolutejs/devices/runtime';
import { createExpoDeviceAdapter } from '@absolutejs/devices-expo';
${push ? "import { absoluteExpoAuth } from './AbsoluteAuth';" : ''}
${imports.join('\n')}

${pushSource}

export const absoluteExpoDeviceCapabilities = ${JSON.stringify(plan.capabilities)} as const;
export const absoluteExpoDevices = createExpoDeviceAdapter({
	storagePrefix: ${JSON.stringify(`absolutejs.${config.appId}.`)},
	${entries}
});
installDeviceAdapter(absoluteExpoDevices);
export const beforeAbsoluteExpoDeviceSignOut = async () => {
	${push ? 'await absoluteExpoDevices.pushNotifications?.disable();' : ''}
};
${
	push
		? `absoluteExpoAuth.onPrincipalChange(principal => {
	if (!principal) return;
	void absoluteExpoDevices.pushNotifications?.queryPermission().then(permission => permission.state === 'granted' ? absoluteExpoDevices.pushNotifications?.enable() : undefined).catch(() => undefined);
});`
		: ''
}
`;
};

const authRuntimeSource = (auth: AbsoluteMobileAuthManifest, appId: string) => {
	const storageIdentity = createHash('sha256')
		.update(appId)
		.digest('hex')
		.slice(0, 24);

	return `${EXPO_GENERATED_HEADER}import { createAbsoluteExpoAuthClient } from '@absolutejs/auth-expo';
import { createMobileAuthTransport, installAuthClientRuntimeTransport } from '@absolutejs/auth/client/mobile';

export const absoluteExpoAuth = createAbsoluteExpoAuthClient({
	allowedOrigins: [${JSON.stringify(auth.issuer)}],
	clientId: ${JSON.stringify(auth.clientId)},
	issuer: ${JSON.stringify(auth.issuer)},
	redirectUri: ${JSON.stringify(auth.redirectUri)},
	resource: ${JSON.stringify(auth.issuer)},
	scopes: ${JSON.stringify(auth.scopes)},
	storagePrefix: ${JSON.stringify(`absolutejs.auth.${storageIdentity}`)}
});
installAuthClientRuntimeTransport(createMobileAuthTransport(absoluteExpoAuth, { baseUrl: ${JSON.stringify(auth.issuer)} }));

let currentPrincipal: Awaited<ReturnType<typeof absoluteExpoAuth.principal>> = null;
absoluteExpoAuth.onPrincipalChange(principal => {
	currentPrincipal = principal;
});
export const getAbsoluteExpoAuthPrincipal = () => currentPrincipal;

let startPromise: Promise<void> | undefined;
export const startAbsoluteExpoAuth = () => {
	startPromise ??= absoluteExpoAuth.start().then(async () => {
		currentPrincipal = await absoluteExpoAuth.principal();
	});

	return startPromise;
};
`;
};

const syncRuntimeSource = (
	config: NormalizedAbsoluteMobileConfig,
	schema: SyncLocalStoreSchemaBundle
) => {
	const storageIdentity = createHash('sha256')
		.update(config.appId)
		.digest('hex')
		.slice(0, 24);
	const backgroundEndpoint = new URL(
		'/__absolute/sync/background',
		config.productionOrigin
	).href;
	const backgroundTask = `${config.appId}.absolutejs.sync`;

	return `${EXPO_GENERATED_HEADER}import { runHeadlessSync } from '@absolutejs/sync/client/headless';
import type { SyncLocalStoreSchemaBundle } from '@absolutejs/sync/client';
import { installSyncClientRuntimeTransport } from '@absolutejs/sync/client/runtime';
import {
	createExpoSyncBridgeHost,
	createExpoSyncLocalStore,
	createExpoSyncProtection,
	createExpoSyncSocketBridgeHost,
	defineExpoSyncBackgroundTask,
	installExpoSyncLifecycle,
	registerExpoSyncBackgroundTask
} from '@absolutejs/sync-expo';
import * as Updates from 'expo-updates';
import { absoluteExpoAuth, startAbsoluteExpoAuth } from './AbsoluteAuth';

const BACKGROUND_TASK = ${JSON.stringify(backgroundTask)};
const BACKGROUND_ENDPOINT = ${JSON.stringify(backgroundEndpoint)};
const PRODUCTION_ORIGIN = ${JSON.stringify(config.productionOrigin)};
const STORAGE_SCHEMA: SyncLocalStoreSchemaBundle = ${JSON.stringify(schema)};
const store = createExpoSyncLocalStore({
	databaseName: ${JSON.stringify(`absolutejs-sync-${storageIdentity}.db`)},
	protection: createExpoSyncProtection({ storagePrefix: ${JSON.stringify(`absolutejs.sync.${storageIdentity}`)} }),
	storageSchema: STORAGE_SCHEMA
});

const runBackgroundSync = async () => {
	await startAbsoluteExpoAuth();
	const principal = await absoluteExpoAuth.principal();
	if (!principal) return;
	await runHeadlessSync({
		endpoint: BACKGROUND_ENDPOINT,
		fetch: (url, init) => absoluteExpoAuth.fetch(url, init),
		namespace: principal.namespace,
		store
	});
};
defineExpoSyncBackgroundTask(BACKGROUND_TASK, runBackgroundSync);

let activeNamespace: string | undefined;
let started = false;
let startPromise: Promise<void> | undefined;
export const startAbsoluteExpoSync = () => {
	startPromise ??= (async () => {
		await startAbsoluteExpoAuth();
		const principal = await absoluteExpoAuth.principal();
		activeNamespace = principal?.namespace;
		installSyncClientRuntimeTransport({
			...(principal ? { durable: { namespace: principal.namespace, store }, socketTicket: () => absoluteExpoAuth.socketTicket() } : {}),
			registerClient: client => installExpoSyncLifecycle({ client })
		});
		await registerExpoSyncBackgroundTask(BACKGROUND_TASK, { minimumInterval: 15 });
		started = true;
	})();

	return startPromise;
};

absoluteExpoAuth.onPrincipalChange(principal => {
	if (!started || principal?.namespace === activeNamespace) return;
	void Updates.reloadAsync();
});

export const createAbsoluteExpoSyncBridge = async (
	emit: (event: 'sync.socket' | 'sync.wake', payload: Record<string, unknown>) => void
) => {
	await startAbsoluteExpoSync();
	const principal = await absoluteExpoAuth.principal();
	if (!principal) return {
		close: () => undefined,
		request: async () => { throw new Error('Expo Sync requires an authenticated principal.'); }
	};
	const transactions = createExpoSyncBridgeHost({ namespace: principal.namespace, store });
	const sockets = createExpoSyncSocketBridgeHost({
		allowedOrigin: PRODUCTION_ORIGIN,
		emit: payload => emit('sync.socket', payload),
		socketTicket: audience => absoluteExpoAuth.socketTicket(audience)
	});
	const removeLifecycle = installExpoSyncLifecycle({
		client: { reconnect: () => emit('sync.wake', {}) }
	});

	return {
		close: async () => {
			removeLifecycle();
			await Promise.all([transactions.close(), sockets.close()]);
		},
		request: (method: string, params: Record<string, unknown>) =>
			method.startsWith('sync.socket.')
				? sockets.request(method, params)
				: transactions.request(method, params)
	};
};
`;
};

const webHostSource = (
	config: NormalizedAbsoluteMobileConfig,
	auth: AbsoluteMobileAuthManifest | undefined,
	sync: boolean
) => {
	const nativeRoutes = [
		'/__absolute/native',
		...Object.keys(config.expoNativeRoutes)
	];
	const nativeRoutePatterns = nativeRoutes.map((route) =>
		route.split('/').filter(Boolean)
	);

	return `${EXPO_GENERATED_HEADER}import * as Linking from 'expo-linking';
import { router, usePathname } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, BackHandler, Platform, StyleSheet, View } from 'react-native';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';
import { materializeAbsoluteWebBundle } from './webAssets';
import { createExpoDevicesBridgeHost } from '@absolutejs/devices-expo/bridge';
import { absoluteExpoDevices, beforeAbsoluteExpoDeviceSignOut } from './AbsoluteDevices';
${auth ? "import { absoluteExpoAuth, getAbsoluteExpoAuthPrincipal, startAbsoluteExpoAuth } from './AbsoluteAuth';" : ''}
${sync ? "import { createAbsoluteExpoSyncBridge, startAbsoluteExpoSync } from './AbsoluteSync';" : ''}

const BRIDGE_FORMAT = 3;
const MAX_MESSAGE_BYTES = 64 * 1024;
const MAX_HTTP_BODY_BYTES = 48 * 1024;
const NATIVE_ROUTE_PATTERNS = ${JSON.stringify(nativeRoutePatterns)};
const PRODUCTION_ORIGIN = ${JSON.stringify(config.productionOrigin)};
const DEV_ORIGIN = Platform.OS === 'android'
	? process.env.EXPO_PUBLIC_ABSOLUTE_DEV_ANDROID_ORIGIN
	: process.env.EXPO_PUBLIC_ABSOLUTE_DEV_IOS_ORIGIN;
const HMR_TARGET = Platform.OS === 'android' ? 'expo-android' : 'expo-ios';
const AUTH_ENABLED = ${auth ? 'true' : 'false'};
const SYNC_ENABLED = ${sync ? 'true' : 'false'};

const isNativeRoute = (pathname: string) => {
	const segments = pathname.split('/').filter(Boolean);
	return NATIVE_ROUTE_PATTERNS.some(pattern => {
		for (let index = 0; index < pattern.length; index += 1) {
			const expected = pattern[index]!;
			if (expected === '*') return segments.length > index;
			if (segments[index] === undefined) return false;
			if (!expected.startsWith(':') && expected !== segments[index]) return false;
		}
		return segments.length === pattern.length;
	});
};

const bridgeBootstrap = (path: string) => {
	const initialPath = DEV_ORIGIN
		? 'location.pathname + location.search + location.hash'
		: JSON.stringify(path);
	return \`(() => {
	const pending = new Map();
	const listeners = new Map();
	let sequence = 0;
	let currentPath = \${initialPath};
	const send = value => {
		const source = JSON.stringify(value);
		if (new TextEncoder().encode(source).byteLength > 65536) throw new Error('Expo bridge message exceeds 64 KiB.');
		window.ReactNativeWebView.postMessage(source);
	};
	globalThis.__absoluteExpoReceive = source => {
		const message = JSON.parse(source);
		if (message.kind === 'event') {
			for (const listener of listeners.get(message.event) || []) listener(message.payload || {});
			return;
		}
		const operation = pending.get(message.id);
		if (!operation) return;
		pending.delete(message.id);
		clearTimeout(operation.timer);
		message.error ? operation.reject(new Error(message.error.message)) : operation.resolve(message.result);
	};
	globalThis.__absoluteExpoBridge = {
		on(event, listener) {
			const values = listeners.get(event) || new Set();
			values.add(listener);
			listeners.set(event, values);
			return () => {
				values.delete(listener);
				if (values.size === 0) listeners.delete(event);
			};
		},
		request(method, params) {
			const id = 'web_' + Date.now().toString(36) + '_' + (++sequence).toString(36);
			send({ format: 3, id, kind: 'request', method, params, path: currentPath });
			return new Promise((resolve, reject) => {
				const interactive = method.startsWith('devices.camera.') || method.startsWith('devices.photos.') || method.startsWith('devices.documents.') || method.endsWith('.requestPermission');
				const timer = setTimeout(() => {
					pending.delete(id);
					reject(new Error('Expo bridge request timed out.'));
				}, interactive ? 5 * 60 * 1000 : 30 * 1000);
				pending.set(id, { reject, resolve, timer });
			});
		},
		setPath(path) {
			currentPath = path;
			send({ format: 3, kind: 'event', event: 'navigation', path });
		}
	};
	if (\${DEV_ORIGIN ? 'true' : 'false'}) {
		const publishPath = () => {
			const path = location.pathname + location.search + location.hash;
			if (path === currentPath) return;
			currentPath = path;
			send({ format: 3, kind: 'event', event: 'navigation', path });
		};
		for (const method of ['pushState', 'replaceState']) {
			const original = history[method];
			history[method] = function(...args) {
				const result = original.apply(this, args);
				publishPath();
				return result;
			};
		}
		addEventListener('popstate', publishPath);
		addEventListener('hashchange', publishPath);
	}
	document.addEventListener('click', event => {
		const anchor = event.target instanceof Element ? event.target.closest('a[href]') : null;
		if (!anchor) return;
		const url = new URL(anchor.href, location.href);
		if (!isNativeRoute(url.pathname)) return;
		event.preventDefault();
		send({ format: 3, kind: 'event', event: 'navigation', path: url.pathname + url.search + url.hash });
	}, true);
	send({ format: 3, kind: 'event', event: 'ready', path: currentPath });
})(); true;\`;
};

const bridgeFetch = async (params: Record<string, unknown>) => {
	if (typeof params.method !== 'string' || !['DELETE', 'GET', 'PATCH', 'POST', 'PUT'].includes(params.method) || typeof params.url !== 'string' || typeof params.headers !== 'object' || params.headers === null || Array.isArray(params.headers) || params.body !== undefined && typeof params.body !== 'string') throw new Error('Expo bridge HTTP request is invalid.');
	const url = new URL(params.url);
	if (url.origin !== PRODUCTION_ORIGIN || url.username || url.password) throw new Error('Expo bridge HTTP request left productionOrigin.');
	const headers = new Headers();
	for (const [name, value] of Object.entries(params.headers as Record<string, unknown>)) {
		const normalized = name.toLowerCase();
		if (typeof value !== 'string' || (normalized !== 'accept' && normalized !== 'content-type' && !normalized.startsWith('x-absolute-mobile-'))) throw new Error('Expo bridge HTTP header is not allowed.');
		headers.set(normalized, value);
	}
	const response = await ${auth ? 'absoluteExpoAuth.fetchOptional' : 'fetch'}(url, { ...(typeof params.body === 'string' ? { body: params.body } : {}), headers, method: params.method, redirect: 'manual' });
	if (new URL(response.url || url.href).origin !== PRODUCTION_ORIGIN || response.status >= 300 && response.status < 400) throw new Error('Expo bridge HTTP redirects are not allowed.');
	const body = await response.text();
	if (new TextEncoder().encode(body).byteLength > MAX_HTTP_BODY_BYTES) throw new Error('Expo bridge HTTP response exceeds 48 KiB.');
	const responseHeaders: Record<string, string> = {};
	for (const name of ['cache-control', 'content-type']) {
		const value = response.headers.get(name);
		if (value) responseHeaders[name] = value;
	}
	return { body, headers: responseHeaders, status: response.status };
};

const authStatus = async () => {
	${
		auth
			? `const user = await absoluteExpoAuth.status();
	const principal = getAbsoluteExpoAuthPrincipal();
	return { principal: principal ? { namespace: principal.namespace } : null, user };`
			: "throw new Error('Expo Auth is not configured.');"
	}
};

export function AbsoluteWebHost() {
	const pathname = usePathname() || '/';
	const webView = useRef<WebView>(null);
	const devicesBridge = useRef<{ close(): void | Promise<void>; request(method: string, params: Record<string, unknown>): Promise<unknown> } | undefined>(undefined);
	const syncBridge = useRef<{ close(): void | Promise<void>; request(method: string, params: Record<string, unknown>): Promise<unknown> } | undefined>(undefined);
	const [indexUri, setIndexUri] = useState<string>();
	const [canGoBack, setCanGoBack] = useState(false);
	const [runtimeReady, setRuntimeReady] = useState(!AUTH_ENABLED && !SYNC_ENABLED);
	const [devicesReady, setDevicesReady] = useState(false);
	const activeWebPath = useRef(pathname);

	useEffect(() => {
		if (!AUTH_ENABLED && !SYNC_ENABLED) return;
		let active = true;
		${
			auth
				? `const stop = absoluteExpoAuth.onPrincipalChange(principal => {
			if (!active) return;
			const source = JSON.stringify({ event: 'auth.principal', format: BRIDGE_FORMAT, kind: 'event', path: activeWebPath.current, payload: { principal: principal ? { namespace: principal.namespace } : null } });
			webView.current?.injectJavaScript(\`globalThis.__absoluteExpoReceive(\${JSON.stringify(source)}); true;\`);
		});
		void ${sync ? 'startAbsoluteExpoSync' : 'startAbsoluteExpoAuth'}().then(async () => {
			${
				sync
					? `syncBridge.current = await createAbsoluteExpoSyncBridge((event, payload) => {
				const source = JSON.stringify({ event, format: BRIDGE_FORMAT, kind: 'event', path: activeWebPath.current, payload });
				webView.current?.injectJavaScript(\`globalThis.__absoluteExpoReceive(\${JSON.stringify(source)}); true;\`);
			});`
					: ''
			}
			if (active) setRuntimeReady(true);
		});
		return () => {
			active = false;
			stop();
			const bridge = syncBridge.current;
			syncBridge.current = undefined;
			void bridge?.close();
		};`
				: ''
		}
	}, []);

	useEffect(() => {
		if (DEV_ORIGIN) {
			const target = new URL(pathname, DEV_ORIGIN);
			target.searchParams.set('__absolute_target', HMR_TARGET);
			setIndexUri(target.href);
			return;
		}
		void materializeAbsoluteWebBundle().then(uri => setIndexUri(uri + '?absolutePath=' + encodeURIComponent(pathname)));
	}, [pathname]);
	useEffect(() => {
		const subscription = BackHandler.addEventListener('hardwareBackPress', () => {
			if (!canGoBack) return false;
			webView.current?.goBack();
			return true;
		});
		return () => subscription.remove();
	}, [canGoBack]);

	const respond = (message: Record<string, unknown>) => {
		const source = JSON.stringify(message).replaceAll('\\u2028', '\\\\u2028').replaceAll('\\u2029', '\\\\u2029');
		if (new TextEncoder().encode(source).byteLength > MAX_MESSAGE_BYTES) throw new Error('Expo bridge response exceeds 64 KiB.');
		webView.current?.injectJavaScript(\`globalThis.__absoluteExpoReceive(\${JSON.stringify(source)}); true;\`);
	};
	useEffect(() => {
		let active = true;
		void createExpoDevicesBridgeHost(absoluteExpoDevices, (event, payload) => {
			if (!active) return;
			respond({ event, format: BRIDGE_FORMAT, kind: 'event', path: activeWebPath.current, payload });
		}).then(host => {
			if (!active) return void host.close();
			devicesBridge.current = host;
			setDevicesReady(true);
		});
		return () => {
			active = false;
			const host = devicesBridge.current;
			devicesBridge.current = undefined;
			void host?.close();
		};
	}, []);
	const hasOrigin = (source: string, origin: string) => {
		try { return new URL(source).origin === origin; } catch { return false; }
	};
	const onMessage = async (event: WebViewMessageEvent) => {
		const source = event.nativeEvent.data;
		if (new TextEncoder().encode(source).byteLength > MAX_MESSAGE_BYTES) return;
		let message: Record<string, unknown>;
		try { message = JSON.parse(source); } catch { return; }
		if (message.format !== BRIDGE_FORMAT || typeof message.path !== 'string' || !message.path.startsWith('/') || message.path.startsWith('//')) return;
		if (message.kind === 'event' && (message.event === 'navigation' || message.event === 'ready')) {
			const target = new URL(message.path, PRODUCTION_ORIGIN);
			if (target.origin !== PRODUCTION_ORIGIN) return;
			if (isNativeRoute(target.pathname)) router.push(message.path as never);
			else activeWebPath.current = message.path;
			return;
		}
		if (message.kind !== 'request' || typeof message.id !== 'string' || message.path !== activeWebPath.current) return;
		try {
			if (typeof message.params !== 'object' || message.params === null || Array.isArray(message.params)) throw new Error('Expo bridge method params are invalid.');
			if (typeof message.method === 'string' && message.method.startsWith('devices.')) {
				if (!devicesBridge.current) throw new Error('Expo devices bridge is unavailable.');
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await devicesBridge.current.request(message.method, message.params as Record<string, unknown>) });
			} else if (message.method === 'http.fetch') {
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await bridgeFetch(message.params as Record<string, unknown>) });
			} else if (message.method === 'auth.signIn') {
				${
					auth
						? `const params = message.params as Record<string, unknown>;
				if (typeof params.email !== 'string' || typeof params.signup !== 'boolean') throw new Error('Expo Auth sign-in params are invalid.');
				await absoluteExpoAuth.signIn({ authorizationParameters: { login_hint: params.email, ...(params.signup ? { screen_hint: 'signup' } : {}) } });
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await authStatus() });`
						: "throw new Error('Expo Auth is not configured.');"
				}
			} else if (message.method === 'auth.signOut') {
				${
					auth
						? `await beforeAbsoluteExpoDeviceSignOut();
				await absoluteExpoAuth.signOut();
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: null });`
						: "throw new Error('Expo Auth is not configured.');"
				}
			} else if (message.method === 'auth.status') {
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await authStatus() });
			} else if (typeof message.method === 'string' && message.method.startsWith('sync.')) {
				if (!syncBridge.current) throw new Error('Expo Sync bridge is unavailable.');
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await syncBridge.current.request(message.method, message.params as Record<string, unknown>) });
			} else {
				throw new Error('Expo bridge method is not allowed.');
			}
		} catch (error) {
			respond({ error: { code: 'failed', message: error instanceof Error ? error.message : 'Native operation failed.' }, format: BRIDGE_FORMAT, id: message.id, kind: 'response' });
		}
	};

	if (!indexUri || !runtimeReady || !devicesReady) return <View style={styles.loading}><ActivityIndicator /></View>;
	return <WebView
		allowFileAccess
		allowFileAccessFromFileURLs
		allowUniversalAccessFromFileURLs={false}
		allowingReadAccessToURL={indexUri.slice(0, indexUri.lastIndexOf('/') + 1)}
		injectedJavaScriptBeforeContentLoaded={bridgeBootstrap(pathname)}
		onMessage={onMessage}
		onNavigationStateChange={state => setCanGoBack(state.canGoBack)}
		onShouldStartLoadWithRequest={request => {
			if (request.url.startsWith('file:') || hasOrigin(request.url, PRODUCTION_ORIGIN) || DEV_ORIGIN && hasOrigin(request.url, DEV_ORIGIN)) return true;
			void Linking.openURL(request.url);
			return false;
		}}
		ref={webView}
		source={{ uri: indexUri }}
		style={styles.web}
	/>;
}

const styles = StyleSheet.create({ loading: { alignItems: 'center', flex: 1, justifyContent: 'center' }, web: { flex: 1 } });
`;
};

const webRouteSource = `${EXPO_GENERATED_HEADER}import { AbsoluteWebHost } from '../src/generated/AbsoluteWebHost';

export default AbsoluteWebHost;
`;

const catchAllRouteSource = `${EXPO_GENERATED_HEADER}import { AbsoluteWebHost } from '../src/generated/AbsoluteWebHost';

export default AbsoluteWebHost;
`;

const nativeRouteRuntimeSource = (auth: boolean) =>
	`${EXPO_GENERATED_HEADER}import { useLocalSearchParams, usePathname } from 'expo-router';
import { type ComponentType, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { ABSOLUTE_MOBILE_MANIFEST } from './webAssets';
${auth ? "import { absoluteExpoAuth } from './AbsoluteAuth';" : ''}

const PAGE_MEDIA_TYPE = 'application/vnd.absolute.page+json';
const NATIVE_DATA_MEDIA_TYPE = 'application/vnd.absolute.native-route+json';
const PROTOCOL = 1;
const MAX_DATA_BYTES = 1024 * 1024;
const DEV_ORIGIN = Platform.OS === 'android'
	? process.env.EXPO_PUBLIC_ABSOLUTE_DEV_ANDROID_ORIGIN
	: process.env.EXPO_PUBLIC_ABSOLUTE_DEV_IOS_ORIGIN;

type RouteParams = Record<string, string | string[] | undefined>;
type NativeRouteProps<PageProps extends object, Params extends object> = {
	pageProps: Readonly<PageProps>;
	params: Readonly<Params>;
	reload: () => void;
};
type NativeRouteState<PageProps> =
	| { kind: 'loading' }
	| { kind: 'ready'; pageProps: PageProps }
	| { kind: 'error' };

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === 'object' && value !== null && !Array.isArray(value);
const routeSegmentPattern = (segment: string) => {
	if (segment === '*') return '.*';
	if (segment.startsWith(':') && segment.endsWith('?')) return '[^/]*';
	if (segment.startsWith(':')) return '[^/]+';
	return segment.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&');
};
const matchesRoute = (pattern: string, pathname: string) =>
	new RegExp('^' + pattern.split('/').map(routeSegmentPattern).join('/') + '/?$').test(pathname);
const requestPathFor = (pathname: string, params: RouteParams, pattern: string) => {
	const pathNames = new Set(pattern.split('/').filter(segment => segment.startsWith(':')).map(segment => segment.replace(/^:/, '').replace(/\\?$/, '')));
	if (pattern.endsWith('/*')) pathNames.add('absoluteWildcard');
	const query = new URLSearchParams();
	for (const [name, value] of Object.entries(params).sort(([left], [right]) => left.localeCompare(right))) {
		if (pathNames.has(name) || name === '#' || value === undefined) continue;
		for (const item of Array.isArray(value) ? value : [value]) query.append(name, item);
	}
	const search = query.toString();
	return pathname + (search ? '?' + search : '');
};
const productionPage = (pathname: string) => {
	if (!ABSOLUTE_MOBILE_MANIFEST) throw new Error('AbsoluteJS native route data is not prepared for production.');
	const route = ABSOLUTE_MOBILE_MANIFEST.routes.find(candidate => candidate.method === 'GET' && matchesRoute(candidate.pattern, pathname));
	if (!route) throw new Error('No trusted AbsoluteJS page route owns this native URL.');
	const page = ABSOLUTE_MOBILE_MANIFEST.pages.find(candidate => candidate.pageId === route.pageId);
	if (!page) throw new Error('The embedded AbsoluteJS page contract is incomplete.');
	return page;
};
const createDataRequest = (path: string) => {
	const development = typeof DEV_ORIGIN === 'string' && DEV_ORIGIN.length > 0;
	const origin = development ? DEV_ORIGIN : ABSOLUTE_MOBILE_MANIFEST?.productionOrigin;
	if (!origin) throw new Error('AbsoluteJS native route data has no trusted server origin.');
	const url = new URL(path, origin);
	if (url.origin !== new URL(origin).origin) throw new Error('AbsoluteJS native route data left its trusted origin.');
	const headers = new Headers();
	headers.set('accept', development ? NATIVE_DATA_MEDIA_TYPE : PAGE_MEDIA_TYPE);
	headers.set('x-absolute-mobile-protocol', String(PROTOCOL));
	let page: ReturnType<typeof productionPage> | undefined;
	if (!development) {
		page = productionPage(url.pathname);
		headers.set('x-absolute-mobile-app-build', ABSOLUTE_MOBILE_MANIFEST!.appBuild);
		headers.set('x-absolute-mobile-page-bundle', page.bundleHash);
		headers.set('x-absolute-mobile-page-contracts', page.contract);
		headers.set('x-absolute-mobile-page-id', page.pageId);
		headers.set('x-absolute-mobile-runtime', ABSOLUTE_MOBILE_MANIFEST!.runtime);
	}
	return { page, request: new Request(url, { headers, method: 'GET' }) };
};
const requestData = async <PageProps extends object>(path: string, signal: AbortSignal) => {
	const { page, request } = createDataRequest(path);
	const response = await ${auth ? 'absoluteExpoAuth.fetchOptional' : 'fetch'}(request, { redirect: 'manual', signal });
	if (new URL(response.url || request.url).origin !== new URL(request.url).origin || response.status >= 300 && response.status < 400) throw new Error('AbsoluteJS native route data redirected outside its contract.');
	const source = await response.text();
	if (new TextEncoder().encode(source).byteLength > MAX_DATA_BYTES) throw new Error('AbsoluteJS native route data exceeded 1 MiB.');
	let envelope: unknown;
	try { envelope = JSON.parse(source); } catch { throw new Error('The server did not return an AbsoluteJS page envelope.'); }
	if (!isRecord(envelope) || envelope.protocol !== PROTOCOL || !isRecord(envelope.response)) throw new Error('The server returned an invalid AbsoluteJS page envelope.');
	const result = envelope.response;
	if (result.kind === 'upgrade-required') throw new Error('This app version must be updated before opening this screen.');
	if (result.kind !== 'page' || !isRecord(result.props) || typeof result.pageId !== 'string' || typeof result.contract !== 'string') throw new Error('The server did not produce native route page props.');
	if (page && (result.pageId !== page.pageId || result.contract !== page.contract)) throw new Error('The server returned a different page contract than this app contains.');
	return result.props as PageProps;
};

export const createAbsoluteNativeRoute = <
	PageProps extends object,
	Params extends object = RouteParams
>(Component: ComponentType<NativeRouteProps<PageProps, Params>>, pattern: string) => {
	function AbsoluteNativeRouteScreen() {
		const pathname = usePathname() || '/';
		const params = useLocalSearchParams() as RouteParams;
		const parameterKey = JSON.stringify(params);
		const requestPath = useMemo(() => requestPathFor(pathname, params, pattern), [parameterKey, pathname]);
		const [revision, setRevision] = useState(0);
		const [state, setState] = useState<NativeRouteState<PageProps>>({ kind: 'loading' });
		useEffect(() => {
			const controller = new AbortController();
			setState({ kind: 'loading' });
			void requestData<PageProps>(requestPath, controller.signal).then(
				pageProps => { if (!controller.signal.aborted) setState({ kind: 'ready', pageProps }); },
				() => { if (!controller.signal.aborted) setState({ kind: 'error' }); }
			);
			return () => controller.abort();
		}, [requestPath, revision]);
		const reload = () => setRevision(value => value + 1);
		if (state.kind === 'loading') return <View style={styles.center}><ActivityIndicator accessibilityLabel="Loading screen" /></View>;
		if (state.kind === 'error') return <View style={styles.center}><Text accessibilityRole="alert" style={styles.error}>This screen could not load.</Text><Pressable accessibilityRole="button" onPress={reload} style={styles.button}><Text>Try again</Text></Pressable></View>;
		return <Component pageProps={state.pageProps} params={params as Params} reload={reload} />;
	}
	return AbsoluteNativeRouteScreen;
};

const styles = StyleSheet.create({
	button: { backgroundColor: '#e2e8f0', borderRadius: 10, paddingHorizontal: 16, paddingVertical: 12 },
	center: { alignItems: 'center', flex: 1, gap: 16, justifyContent: 'center', padding: 24 },
	error: { color: '#b91c1c', fontSize: 16, textAlign: 'center' }
});
`;

const nativeWrapperSource = (
	wrapper: string,
	module: string,
	runtime: string,
	route: string
) =>
	`${EXPO_GENERATED_HEADER}import ApplicationNativeRoute from ${JSON.stringify(portableRelative(dirname(wrapper), module).replace(/\.(?:[cm]?[jt]sx?)$/u, ''))};
import { createAbsoluteNativeRoute } from ${JSON.stringify(portableRelative(dirname(wrapper), runtime).replace(/\.(?:[cm]?[jt]sx?)$/u, ''))};

export default createAbsoluteNativeRoute(ApplicationNativeRoute, ${JSON.stringify(route)});
`;

const expoTsConfig = (
	projectRoot: string,
	project: string,
	auth: boolean,
	sync: boolean
) => ({
	compilerOptions: {
		paths: {
			...(auth
				? {
						'@absolutejs/auth': [
							'./node_modules/@absolutejs/auth/dist/index.d.ts'
						],
						'@absolutejs/auth/*': [
							'./node_modules/@absolutejs/auth/dist/*'
						]
					}
				: {}),
			...(sync
				? {
						'@absolutejs/sync': [
							'./node_modules/@absolutejs/sync/dist/index.d.ts'
						],
						'@absolutejs/sync-expo': [
							'./node_modules/@absolutejs/sync-expo/dist/index.d.ts'
						],
						'@absolutejs/sync-expo/*': [
							'./node_modules/@absolutejs/sync-expo/dist/*'
						],
						'@absolutejs/sync/*': [
							'./node_modules/@absolutejs/sync/dist/*'
						]
					}
				: {}),
			'*': [
				'./node_modules/*',
				`${portableRelative(project, projectRoot)}/node_modules/*`
			],
			react: ['./node_modules/@types/react/index.d.ts'],
			'react/*': ['./node_modules/@types/react/*']
		},
		strict: true
	},
	extends: 'expo/tsconfig.base'
});

const writeManagedFile = async (
	path: string,
	source: string,
	force: boolean
) => {
	await mkdir(dirname(path), { recursive: true });
	if (await exists(path)) {
		const current = await readFile(path, 'utf8');
		if (current === source) return false;
		if (!force && !current.startsWith(EXPO_GENERATED_HEADER)) {
			throw new TypeError(
				`Expo project file ${path} is not AbsoluteJS-managed; rerun with --force only after reviewing it.`
			);
		}
	}
	const temporary = `${path}.${crypto.randomUUID()}.tmp`;
	await writeFile(temporary, source, { flag: 'wx' });
	await rename(temporary, path);

	return true;
};

const pruneStaleManagedExpoRoutes = async (
	project: string,
	expected: ReadonlySet<string>
) => {
	const appDirectory = join(project, 'app');
	if (!(await exists(appDirectory))) return 0;
	const files = await walkFiles(appDirectory);
	const stale = (
		await Promise.all(
			files.map(async (path) => ({
				managed:
					path.endsWith('.tsx') &&
					(await readFile(path, 'utf8')).startsWith(
						EXPO_GENERATED_HEADER
					),
				path
			}))
		)
	).filter(({ managed, path }) => managed && !expected.has(path));
	await Promise.all(stale.map(({ path }) => rm(path, { force: true })));

	return stale.length;
};

const jsonSource = (value: unknown) => `${JSON.stringify(value, null, '\t')}\n`;

const nativeDataManifestTypeSource = `type AbsoluteMobileManifest = {
	appBuild: string;
	pages: readonly { bundleHash: string; contract: string; pageId: string }[];
	productionOrigin: string;
	routes: readonly { method: 'GET'; pageId: string; pattern: string }[];
	runtime: string;
};
`;

const emptyWebAssetsSource = `${EXPO_GENERATED_HEADER}${nativeDataManifestTypeSource}
export const materializeAbsoluteWebBundle = async () => {
	throw new Error('The embedded AbsoluteJS bundle is unavailable. Run absolute prepare before a production Expo build.');
};
export const ABSOLUTE_MOBILE_MANIFEST: AbsoluteMobileManifest | undefined = undefined;
`;

export const writeAbsoluteExpoProject = async (
	config: NormalizedAbsoluteMobileConfig,
	options: WriteAbsoluteExpoProjectOptions
) => {
	if (config.engine !== 'expo')
		throw new TypeError(
			'Expo project generation requires mobile.engine: expo.'
		);
	const projectRoot = resolve(options.projectRoot);
	const project = config.nativeProjectDirectory;
	const auth = resolveAbsoluteMobileAuthManifest(projectRoot, config);
	const devices = resolveAbsoluteDeviceCapabilityPlan(projectRoot, 'expo');
	const syncEnabled = Boolean(auth && projectUsesAbsoluteSync(projectRoot));
	const syncSchema = syncEnabled
		? { components: discoverAbsoluteSyncSchema(projectRoot).components }
		: undefined;
	const routeModules = Object.entries(config.expoNativeRoutes);
	const moduleChecks = await Promise.all(
		routeModules.map(async ([route, module]) => ({
			exists: await exists(module),
			module,
			route
		}))
	);
	const missing = moduleChecks.find((entry) => !entry.exists);
	if (missing) {
		throw new TypeError(
			`Expo native route ${missing.route} references missing module ${missing.module}.`
		);
	}
	const marker = join(project, EXPO_PROJECT_MARKER);
	if ((await exists(project)) && !(await exists(marker))) {
		const entries = await readdir(project);
		if (entries.length > 0 && !options.force) {
			throw new TypeError(
				`Expo project directory ${project} is not AbsoluteJS-managed; rerun with --force only after reviewing it.`
			);
		}
	}
	await mkdir(project, { recursive: true });
	await writeFile(marker, 'format=1\n');
	const authEnabled = Boolean(auth);
	const files = new Map<string, string>([
		[
			join(project, '.gitignore'),
			'.expo/\nandroid/\nios/\nnode_modules/\n'
		],
		[
			join(project, 'app.json'),
			jsonSource(expoAppConfig(config, authEnabled, syncEnabled, devices))
		],
		[join(project, 'app.config.js'), expoDynamicAppConfig],
		[
			join(project, 'package.json'),
			jsonSource(expoPackage(authEnabled, syncEnabled, devices))
		],
		[join(project, 'metro.config.js'), metroConfig(projectRoot)],
		[
			join(project, 'plugins', 'withAbsoluteDevelopmentCa.js'),
			expoDevelopmentCaPlugin
		],
		[
			join(project, 'tsconfig.json'),
			jsonSource(
				expoTsConfig(projectRoot, project, authEnabled, syncEnabled)
			)
		],
		[
			join(project, 'app', '_layout.tsx'),
			layoutSource(authEnabled, syncEnabled)
		],
		[
			join(project, 'app', '__absolute', 'native', 'index.tsx'),
			nativeDiagnosticSource
		],
		[
			join(project, 'src', 'generated', 'AbsoluteDevices.ts'),
			devicesRuntimeSource(config, devices, authEnabled)
		],
		[
			join(project, 'src', 'generated', 'AbsoluteNativeRoute.tsx'),
			nativeRouteRuntimeSource(authEnabled)
		],
		[
			join(project, 'src', 'generated', 'AbsoluteWebHost.tsx'),
			webHostSource(config, auth, syncEnabled)
		]
	]);
	if (auth) {
		files.set(
			join(project, 'src', 'generated', 'AbsoluteAuth.ts'),
			authRuntimeSource(auth, config.appId)
		);
	}
	if (syncSchema) {
		files.set(
			join(project, 'src', 'generated', 'AbsoluteSync.ts'),
			syncRuntimeSource(config, syncSchema)
		);
	}
	const webAssetsPath = join(project, 'src', 'generated', 'webAssets.ts');
	if (!(await exists(webAssetsPath))) {
		files.set(webAssetsPath, emptyWebAssetsSource);
	}
	if (!config.expoNativeRoutes['/']) {
		files.set(join(project, 'app', 'index.tsx'), webRouteSource);
	}
	files.set(join(project, 'app', '[...absolute].tsx'), catchAllRouteSource);
	const nativeRouteRuntime = join(
		project,
		'src',
		'generated',
		'AbsoluteNativeRoute.tsx'
	);
	for (const [route, module] of routeModules) {
		const wrapper =
			route === '/'
				? join(project, 'app', 'index.tsx')
				: routeFile(project, route);
		files.set(
			wrapper,
			nativeWrapperSource(wrapper, module, nativeRouteRuntime, route)
		);
	}
	const removed = await pruneStaleManagedExpoRoutes(
		project,
		new Set(
			[...files.keys()].filter((path) =>
				path.startsWith(`${join(project, 'app')}${sep}`)
			)
		)
	);
	const changes = await Promise.all(
		[...files].map(([path, source]) => writeManagedFile(path, source, true))
	);
	const changed = removed + changes.filter(Boolean).length;

	return { changed, path: project, written: [...files.keys()] };
};

const walkFiles = async (root: string, directory = root): Promise<string[]> => {
	const entries = await readdir(directory, { withFileTypes: true });
	const nested = await Promise.all(
		entries.map((entry) => {
			const path = join(directory, entry.name);
			if (entry.isDirectory()) return walkFiles(root, path);
			if (entry.isFile()) return [path];
			throw new TypeError(
				`Expo embedded bundle cannot contain a symbolic link or special file: ${path}.`
			);
		})
	);

	return nested.flat().sort();
};

const renameIfPresent = async (source: string, destination: string) => {
	try {
		await rename(source, destination);

		return true;
	} catch (error) {
		if (
			typeof error === 'object' &&
			error !== null &&
			Reflect.get(error, 'code') === 'ENOENT'
		) {
			return false;
		}
		throw error;
	}
};

const installStagedDirectory = async (staging: string, destination: string) => {
	const backup = `${destination}.previous-${crypto.randomUUID()}`;
	const moved = await renameIfPresent(destination, backup);
	try {
		await rename(staging, destination);
		if (moved) await rm(backup, { force: true, recursive: true });
	} catch (error) {
		if (moved) await rename(backup, destination);
		throw error;
	}
};

const assetModuleSource = (
	assets: AbsoluteExpoAssetEntry[],
	bundleId: string,
	manifest: AbsoluteExpoNativeDataManifest
) => `${EXPO_GENERATED_HEADER}import { Asset } from 'expo-asset';
import { Directory, File, Paths } from 'expo-file-system';

${nativeDataManifestTypeSource}
declare const require: (path: string) => number;
const BUNDLE_ID = ${JSON.stringify(bundleId)};
export const ABSOLUTE_MOBILE_MANIFEST: AbsoluteMobileManifest = ${JSON.stringify(manifest)};
const ASSETS = [
${assets.map(({ asset, path }) => `\t{ module: require(${JSON.stringify(asset)}), path: ${JSON.stringify(path)} }`).join(',\n')}
] as const;

export const materializeAbsoluteWebBundle = async () => {
	const root = new Directory(Paths.document, 'absolutejs-web', BUNDLE_ID);
	root.create({ idempotent: true, intermediates: true });
	for (const entry of ASSETS) {
		const parts = entry.path.split('/');
		const name = parts.pop();
		if (!name) throw new Error('AbsoluteJS embedded asset path is invalid.');
		const directory = new Directory(root, ...parts);
		directory.create({ idempotent: true, intermediates: true });
		const destination = new File(directory, name);
		if (destination.exists) continue;
		const asset = await Asset.fromModule(entry.module).downloadAsync();
		if (!asset.localUri) throw new Error('Expo did not materialize an embedded AbsoluteJS asset.');
		new File(asset.localUri).copy(destination);
	}

	return new File(root, 'index.html').uri;
};
`;

export const syncAbsoluteExpoWebAssets = async (
	config: NormalizedAbsoluteMobileConfig
) => {
	if (config.engine !== 'expo')
		throw new TypeError('Expo asset sync requires mobile.engine: expo.');
	const marker = join(config.nativeProjectDirectory, EXPO_PROJECT_MARKER);
	if (!(await exists(marker))) {
		throw new TypeError(
			'Expo asset sync requires an AbsoluteJS-managed Expo project. Run mobile init first.'
		);
	}
	const manifestPath = join(
		config.bundleDirectory,
		'absolute-mobile-manifest.json'
	);
	const manifest: unknown = JSON.parse(await readFile(manifestPath, 'utf8'));
	const nativeDataManifest = expoNativeDataManifest(manifest);
	const { appBuild } = nativeDataManifest;
	const files = await walkFiles(config.bundleDirectory);
	const bundleHash = createHash('sha256');
	const filesWithContents = await Promise.all(
		files.map(async (file) => ({ contents: await readFile(file), file }))
	);
	filesWithContents.forEach(({ contents, file }) => {
		bundleHash.update(
			relative(config.bundleDirectory, file).replaceAll('\\', '/')
		);
		bundleHash.update('\0');
		bundleHash.update(contents);
		bundleHash.update('\0');
	});
	const bundleId = `amexpo_${bundleHash.digest('hex')}`;
	const destination = join(
		config.nativeProjectDirectory,
		'assets',
		'absolute'
	);
	await mkdir(dirname(destination), { recursive: true });
	const staging = await mkdtemp(
		join(dirname(destination), `.${basename(destination)}.stage-`)
	);
	let assets: AbsoluteExpoAssetEntry[];
	try {
		assets = await Promise.all(
			files.map(async (source, index) => {
				const name = `${String(index).padStart(6, '0')}${EXPO_ASSET_EXTENSION}`;
				await cp(source, join(staging, name));

				return {
					asset: portableRelative(
						join(config.nativeProjectDirectory, 'src', 'generated'),
						join(destination, name)
					),
					path: relative(config.bundleDirectory, source).replaceAll(
						'\\',
						'/'
					)
				};
			})
		);
		await installStagedDirectory(staging, destination);
	} catch (error) {
		await rm(staging, { force: true, recursive: true });
		throw error;
	}
	const generated = join(
		config.nativeProjectDirectory,
		'src',
		'generated',
		'webAssets.ts'
	);
	await writeManagedFile(
		generated,
		assetModuleSource(assets, bundleId, nativeDataManifest),
		true
	);

	return { appBuild, assets: assets.length, bundleId, path: destination };
};
