import {
	access,
	cp,
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	rename,
	rm,
	writeFile
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { basename, dirname, join, relative, resolve } from 'node:path';
import type { NormalizedAbsoluteMobileConfig } from './config';

const EXPO_GENERATED_HEADER =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';
const EXPO_ASSET_EXTENSION = '.absasset';
const EXPO_PROJECT_MARKER = '.absolutejs-expo-project';

export type WriteAbsoluteExpoProjectOptions = {
	force?: boolean;
	projectRoot: string;
};

const exists = async (path: string) => {
	try {
		await access(path);

		return true;
	} catch {
		return false;
	}
};

const portableRelative = (from: string, destination: string) => {
	const value = relative(from, destination).replaceAll('\\', '/');

	return value.startsWith('.') ? value : `./${value}`;
};

const routeSegments = (route: string) =>
	route
		.split('/')
		.filter(Boolean)
		.map((segment) => {
			if (segment.startsWith(':')) return `[${segment.slice(1)}]`;
			if (
				segment === '.' ||
				segment === '..' ||
				!/^[A-Za-z0-9._~-]+$/u.test(segment)
			) {
				throw new TypeError(
					`Expo native route ${route} contains an unsupported segment ${segment}.`
				);
			}

			return segment;
		});

const routeFile = (project: string, route: string) =>
	join(project, 'app', ...routeSegments(route), 'index.tsx');

const expoPackage = () => ({
	dependencies: {
		expo: '~57.0.9',
		'expo-asset': '~57.0.15',
		'expo-constants': '~57.0.16',
		'expo-dev-client': '~57.0.16',
		'expo-file-system': '~57.0.6',
		'expo-haptics': '~57.0.2',
		'expo-linking': '~57.0.8',
		'expo-router': '~57.0.17',
		react: '19.2.3',
		'react-native': '0.86.3',
		'react-native-safe-area-context': '~5.7.0',
		'react-native-screens': '4.26.0',
		'react-native-webview': '13.16.1'
	},
	devDependencies: {
		'@types/react': '~19.2.2',
		typescript: '~6.0.3'
	},
	main: 'expo-router/entry',
	name: 'absolutejs-expo-shell',
	private: true,
	scripts: {
		android: 'expo run:android',
		ios: 'expo run:ios',
		start: 'expo start --dev-client'
	},
	version: '0.0.0'
});

const expoAppConfig = (config: NormalizedAbsoluteMobileConfig) => ({
	expo: {
		android: {
			intentFilters: config.deepLinkHosts.map((host) => ({
				action: 'VIEW',
				autoVerify: true,
				category: ['BROWSABLE', 'DEFAULT'],
				data: [{ host, pathPrefix: '/', scheme: 'https' }]
			})),
			package: config.appId
		},
		experiments: { typedRoutes: true },
		ios: {
			associatedDomains: config.deepLinkHosts.map(
				(host) => `applinks:${host}`
			),
			bundleIdentifier: config.appId,
			...(config.iosVersion ? { buildNumber: config.iosVersion } : {})
		},
		name: config.appName,
		plugins: [
			'expo-router',
			['expo-dev-client', { launchMode: 'most-recent' }]
		],
		runtimeVersion: { policy: 'appVersion' },
		scheme: config.deepLinkScheme,
		slug: config.appId.toLowerCase().replaceAll('.', '-'),
		version: config.iosVersion ?? '0.1.0'
	}
});

const metroConfig = (projectRoot: string) =>
	`${EXPO_GENERATED_HEADER}const { getDefaultConfig } = require('expo/metro-config');
const path = require('node:path');

const projectRoot = __dirname;
const appRoot = ${JSON.stringify(projectRoot)};
const config = getDefaultConfig(projectRoot);
config.resolver.assetExts.push('absasset');
config.resolver.nodeModulesPaths = [
	path.join(projectRoot, 'node_modules'),
	path.join(appRoot, 'node_modules')
];
config.watchFolders = [appRoot];

module.exports = config;
`;

const layoutSource = `${EXPO_GENERATED_HEADER}import { Stack } from 'expo-router';

export default function AbsoluteLayout() {
	return <Stack screenOptions={{ headerShown: false }} />;
}
`;

const nativeDiagnosticSource = `${EXPO_GENERATED_HEADER}import * as Haptics from 'expo-haptics';
import { Link } from 'expo-router';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

export default function AbsoluteNativeDiagnostic() {
	return (
		<SafeAreaView style={styles.page}>
			<View style={styles.card}>
				<Text style={styles.eyebrow}>ABSOLUTEJS · EXPO EXPERIMENT</Text>
				<Text style={styles.title}>This screen is native React UI.</Text>
				<Text style={styles.body}>Ordinary AbsoluteJS routes remain embedded web routes. Only explicitly owned routes use React Native.</Text>
				<Pressable style={styles.button} onPress={() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)}>
					<Text style={styles.buttonText}>Test native haptics</Text>
				</Pressable>
				<Link href="/" style={styles.link}>Open the AbsoluteJS app</Link>
			</View>
		</SafeAreaView>
	);
}

const styles = StyleSheet.create({
	body: { color: '#cbd5e1', fontSize: 16, lineHeight: 24 },
	button: { backgroundColor: '#f8fafc', borderRadius: 12, padding: 14 },
	buttonText: { color: '#020617', fontSize: 16, fontWeight: '700', textAlign: 'center' },
	card: { backgroundColor: '#0f172a', borderRadius: 24, gap: 20, maxWidth: 560, padding: 28, width: '100%' },
	eyebrow: { color: '#38bdf8', fontSize: 12, fontWeight: '800', letterSpacing: 1.5 },
	link: { color: '#7dd3fc', fontSize: 16, textAlign: 'center' },
	page: { alignItems: 'center', backgroundColor: '#020617', flex: 1, justifyContent: 'center', padding: 20 },
	title: { color: '#f8fafc', fontSize: 32, fontWeight: '800' }
});
`;

const webHostSource = (config: NormalizedAbsoluteMobileConfig) => {
	const nativeRoutes = [
		'/__absolute/native',
		...Object.keys(config.expoNativeRoutes)
	];

	return `${EXPO_GENERATED_HEADER}import * as Haptics from 'expo-haptics';
import * as Linking from 'expo-linking';
import { router, usePathname } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, BackHandler, Platform, StyleSheet, View } from 'react-native';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';
import { materializeAbsoluteWebBundle } from './webAssets';

const BRIDGE_FORMAT = 1;
const MAX_MESSAGE_BYTES = 64 * 1024;
const MAX_HTTP_BODY_BYTES = 48 * 1024;
const NATIVE_ROUTES = new Set(${JSON.stringify(nativeRoutes)});
const PRODUCTION_ORIGIN = ${JSON.stringify(config.productionOrigin)};
const DEV_ORIGIN = Platform.OS === 'android'
	? process.env.EXPO_PUBLIC_ABSOLUTE_DEV_ANDROID_ORIGIN
	: process.env.EXPO_PUBLIC_ABSOLUTE_DEV_IOS_ORIGIN;
const HMR_TARGET = Platform.OS === 'android' ? 'expo-android' : 'expo-ios';

const bridgeBootstrap = (path: string) => {
	const initialPath = DEV_ORIGIN
		? 'location.pathname + location.search + location.hash'
		: JSON.stringify(path);
	return \`(() => {
	const pending = new Map();
	let sequence = 0;
	let currentPath = \${initialPath};
	const send = value => {
		const source = JSON.stringify(value);
		if (new TextEncoder().encode(source).byteLength > 65536) throw new Error('Expo bridge message exceeds 64 KiB.');
		window.ReactNativeWebView.postMessage(source);
	};
	globalThis.__absoluteExpoReceive = source => {
		const message = JSON.parse(source);
		const operation = pending.get(message.id);
		if (!operation) return;
		pending.delete(message.id);
		clearTimeout(operation.timer);
		message.error ? operation.reject(new Error(message.error.message)) : operation.resolve(message.result);
	};
	globalThis.__absoluteExpoBridge = {
		request(method, params) {
			const id = 'web_' + Date.now().toString(36) + '_' + (++sequence).toString(36);
			send({ format: 1, id, kind: 'request', method, params, path: currentPath });
			return new Promise((resolve, reject) => {
				const timer = setTimeout(() => {
					pending.delete(id);
					reject(new Error('Expo bridge request timed out.'));
				}, 10000);
				pending.set(id, { reject, resolve, timer });
			});
		},
		setPath(path) {
			currentPath = path;
			send({ format: 1, kind: 'event', event: 'navigation', path });
		}
	};
	if (\${DEV_ORIGIN ? 'true' : 'false'}) {
		const publishPath = () => {
			const path = location.pathname + location.search + location.hash;
			if (path === currentPath) return;
			currentPath = path;
			send({ format: 1, kind: 'event', event: 'navigation', path });
		};
		for (const method of ['pushState', 'replaceState']) {
			const original = history[method];
			history[method] = function(...args) {
				const result = original.apply(this, args);
				publishPath();
				return result;
			};
		}
		addEventListener('popstate', publishPath);
		addEventListener('hashchange', publishPath);
	}
	document.addEventListener('click', event => {
		const anchor = event.target instanceof Element ? event.target.closest('a[href]') : null;
		if (!anchor) return;
		const url = new URL(anchor.href, location.href);
		if (!${JSON.stringify(nativeRoutes)}.includes(url.pathname)) return;
		event.preventDefault();
		send({ format: 1, kind: 'event', event: 'navigation', path: url.pathname + url.search + url.hash });
	}, true);
	send({ format: 1, kind: 'event', event: 'ready', path: currentPath });
})(); true;\`;
};

const impact = async (params: Record<string, unknown>) => {
	const style = params.style;
	if (style === 'selection') return Haptics.selectionAsync();
	if (style === 'success' || style === 'warning' || style === 'error') {
		const value = style === 'success' ? Haptics.NotificationFeedbackType.Success : style === 'warning' ? Haptics.NotificationFeedbackType.Warning : Haptics.NotificationFeedbackType.Error;
		return Haptics.notificationAsync(value);
	}
	const value = style === 'light' ? Haptics.ImpactFeedbackStyle.Light : style === 'heavy' ? Haptics.ImpactFeedbackStyle.Heavy : Haptics.ImpactFeedbackStyle.Medium;
	return Haptics.impactAsync(value);
};

const bridgeFetch = async (params: Record<string, unknown>) => {
	if (params.method !== 'GET' || typeof params.url !== 'string' || typeof params.headers !== 'object' || params.headers === null || Array.isArray(params.headers)) throw new Error('Expo bridge HTTP request is invalid.');
	const url = new URL(params.url);
	if (url.origin !== PRODUCTION_ORIGIN || url.username || url.password) throw new Error('Expo bridge HTTP request left productionOrigin.');
	const headers = new Headers();
	for (const [name, value] of Object.entries(params.headers as Record<string, unknown>)) {
		const normalized = name.toLowerCase();
		if (typeof value !== 'string' || (normalized !== 'accept' && !normalized.startsWith('x-absolute-mobile-'))) throw new Error('Expo bridge HTTP header is not allowed.');
		headers.set(normalized, value);
	}
	const response = await fetch(url, { headers, method: 'GET', redirect: 'manual' });
	if (new URL(response.url || url.href).origin !== PRODUCTION_ORIGIN || response.status >= 300 && response.status < 400) throw new Error('Expo bridge HTTP redirects are not allowed.');
	const body = await response.text();
	if (new TextEncoder().encode(body).byteLength > MAX_HTTP_BODY_BYTES) throw new Error('Expo bridge HTTP response exceeds 48 KiB.');
	const responseHeaders: Record<string, string> = {};
	for (const name of ['cache-control', 'content-type']) {
		const value = response.headers.get(name);
		if (value) responseHeaders[name] = value;
	}
	return { body, headers: responseHeaders, status: response.status };
};

export function AbsoluteWebHost() {
	const pathname = usePathname() || '/';
	const webView = useRef<WebView>(null);
	const [indexUri, setIndexUri] = useState<string>();
	const [canGoBack, setCanGoBack] = useState(false);
	const activeWebPath = useRef(pathname);

	useEffect(() => {
		if (DEV_ORIGIN) {
			const target = new URL(pathname, DEV_ORIGIN);
			target.searchParams.set('__absolute_target', HMR_TARGET);
			setIndexUri(target.href);
			return;
		}
		void materializeAbsoluteWebBundle().then(uri => setIndexUri(uri + '?absolutePath=' + encodeURIComponent(pathname)));
	}, [pathname]);
	useEffect(() => {
		const subscription = BackHandler.addEventListener('hardwareBackPress', () => {
			if (!canGoBack) return false;
			webView.current?.goBack();
			return true;
		});
		return () => subscription.remove();
	}, [canGoBack]);

	const respond = (message: Record<string, unknown>) => {
		const source = JSON.stringify(message).replaceAll('\\u2028', '\\\\u2028').replaceAll('\\u2029', '\\\\u2029');
		if (new TextEncoder().encode(source).byteLength > MAX_MESSAGE_BYTES) throw new Error('Expo bridge response exceeds 64 KiB.');
		webView.current?.injectJavaScript(\`globalThis.__absoluteExpoReceive(\${JSON.stringify(source)}); true;\`);
	};
	const hasOrigin = (source: string, origin: string) => {
		try { return new URL(source).origin === origin; } catch { return false; }
	};
	const onMessage = async (event: WebViewMessageEvent) => {
		const source = event.nativeEvent.data;
		if (new TextEncoder().encode(source).byteLength > MAX_MESSAGE_BYTES) return;
		let message: Record<string, unknown>;
		try { message = JSON.parse(source); } catch { return; }
		if (message.format !== BRIDGE_FORMAT || typeof message.path !== 'string' || !message.path.startsWith('/') || message.path.startsWith('//')) return;
		if (message.kind === 'event' && (message.event === 'navigation' || message.event === 'ready')) {
			const target = new URL(message.path, PRODUCTION_ORIGIN);
			if (target.origin !== PRODUCTION_ORIGIN) return;
			if (NATIVE_ROUTES.has(target.pathname)) router.push(message.path as never);
			else activeWebPath.current = message.path;
			return;
		}
		if (message.kind !== 'request' || typeof message.id !== 'string' || message.path !== activeWebPath.current) return;
		try {
			if (typeof message.params !== 'object' || message.params === null || Array.isArray(message.params)) throw new Error('Expo bridge method params are invalid.');
			if (message.method === 'devices.haptics.impact') {
				const style = (message.params as Record<string, unknown>).style;
				if (typeof style !== 'string' || !['error', 'heavy', 'light', 'medium', 'selection', 'success', 'vibrate', 'warning'].includes(style)) throw new Error('Expo bridge haptics style is invalid.');
				await impact(message.params as Record<string, unknown>);
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: null });
			} else if (message.method === 'http.fetch') {
				respond({ format: BRIDGE_FORMAT, id: message.id, kind: 'response', result: await bridgeFetch(message.params as Record<string, unknown>) });
			} else {
				throw new Error('Expo bridge method is not allowed.');
			}
		} catch (error) {
			respond({ error: { code: 'failed', message: error instanceof Error ? error.message : 'Native operation failed.' }, format: BRIDGE_FORMAT, id: message.id, kind: 'response' });
		}
	};

	if (!indexUri) return <View style={styles.loading}><ActivityIndicator /></View>;
	return <WebView
		allowFileAccess
		allowFileAccessFromFileURLs
		allowUniversalAccessFromFileURLs={false}
		allowingReadAccessToURL={indexUri.slice(0, indexUri.lastIndexOf('/') + 1)}
		injectedJavaScriptBeforeContentLoaded={bridgeBootstrap(pathname)}
		onMessage={onMessage}
		onNavigationStateChange={state => setCanGoBack(state.canGoBack)}
		onShouldStartLoadWithRequest={request => {
			if (request.url.startsWith('file:') || hasOrigin(request.url, PRODUCTION_ORIGIN) || DEV_ORIGIN && hasOrigin(request.url, DEV_ORIGIN)) return true;
			void Linking.openURL(request.url);
			return false;
		}}
		ref={webView}
		source={{ uri: indexUri }}
		style={styles.web}
	/>;
}

const styles = StyleSheet.create({ loading: { alignItems: 'center', flex: 1, justifyContent: 'center' }, web: { flex: 1 } });
`;
};

const webRouteSource = `${EXPO_GENERATED_HEADER}import { AbsoluteWebHost } from '../src/generated/AbsoluteWebHost';

export default AbsoluteWebHost;
`;

const catchAllRouteSource = `${EXPO_GENERATED_HEADER}import { AbsoluteWebHost } from '../src/generated/AbsoluteWebHost';

export default AbsoluteWebHost;
`;

const nativeWrapperSource = (wrapper: string, module: string) =>
	`${EXPO_GENERATED_HEADER}export { default } from ${JSON.stringify(portableRelative(dirname(wrapper), module).replace(/\.(?:[cm]?[jt]sx?)$/u, ''))};
`;

const expoTsConfig = (projectRoot: string, project: string) => ({
	compilerOptions: {
		paths: {
			'*': [
				'./node_modules/*',
				`${portableRelative(project, projectRoot)}/node_modules/*`
			],
			react: ['./node_modules/@types/react/index.d.ts'],
			'react/*': ['./node_modules/@types/react/*']
		},
		strict: true
	},
	extends: 'expo/tsconfig.base'
});

const writeManagedFile = async (
	path: string,
	source: string,
	force: boolean
) => {
	await mkdir(dirname(path), { recursive: true });
	if (await exists(path)) {
		const current = await readFile(path, 'utf8');
		if (current === source) return false;
		if (!force && !current.startsWith(EXPO_GENERATED_HEADER)) {
			throw new TypeError(
				`Expo project file ${path} is not AbsoluteJS-managed; rerun with --force only after reviewing it.`
			);
		}
	}
	const temporary = `${path}.${crypto.randomUUID()}.tmp`;
	await writeFile(temporary, source, { flag: 'wx' });
	await rename(temporary, path);

	return true;
};

const jsonSource = (value: unknown) => `${JSON.stringify(value, null, '\t')}\n`;

const emptyWebAssetsSource = `${EXPO_GENERATED_HEADER}export const materializeAbsoluteWebBundle = async () => {
	throw new Error('The embedded AbsoluteJS bundle is unavailable. Run absolute prepare before a production Expo build.');
};
`;

export const writeAbsoluteExpoProject = async (
	config: NormalizedAbsoluteMobileConfig,
	options: WriteAbsoluteExpoProjectOptions
) => {
	if (config.engine !== 'expo')
		throw new TypeError(
			'Expo project generation requires mobile.engine: expo.'
		);
	const projectRoot = resolve(options.projectRoot);
	const project = config.nativeProjectDirectory;
	const routeModules = Object.entries(config.expoNativeRoutes);
	const moduleChecks = await Promise.all(
		routeModules.map(async ([route, module]) => ({
			exists: await exists(module),
			module,
			route
		}))
	);
	const missing = moduleChecks.find((entry) => !entry.exists);
	if (missing) {
		throw new TypeError(
			`Expo native route ${missing.route} references missing module ${missing.module}.`
		);
	}
	const marker = join(project, EXPO_PROJECT_MARKER);
	if ((await exists(project)) && !(await exists(marker))) {
		const entries = await readdir(project);
		if (entries.length > 0 && !options.force) {
			throw new TypeError(
				`Expo project directory ${project} is not AbsoluteJS-managed; rerun with --force only after reviewing it.`
			);
		}
	}
	await mkdir(project, { recursive: true });
	await writeFile(marker, 'format=1\n');
	const files = new Map<string, string>([
		[
			join(project, '.gitignore'),
			'.expo/\nandroid/\nios/\nnode_modules/\n'
		],
		[join(project, 'app.json'), jsonSource(expoAppConfig(config))],
		[join(project, 'package.json'), jsonSource(expoPackage())],
		[join(project, 'metro.config.js'), metroConfig(projectRoot)],
		[
			join(project, 'tsconfig.json'),
			jsonSource(expoTsConfig(projectRoot, project))
		],
		[join(project, 'app', '_layout.tsx'), layoutSource],
		[
			join(project, 'app', '__absolute', 'native', 'index.tsx'),
			nativeDiagnosticSource
		],
		[
			join(project, 'src', 'generated', 'AbsoluteWebHost.tsx'),
			webHostSource(config)
		]
	]);
	const webAssetsPath = join(project, 'src', 'generated', 'webAssets.ts');
	if (!(await exists(webAssetsPath))) {
		files.set(webAssetsPath, emptyWebAssetsSource);
	}
	if (!config.expoNativeRoutes['/']) {
		files.set(join(project, 'app', 'index.tsx'), webRouteSource);
	}
	files.set(join(project, 'app', '[...absolute].tsx'), catchAllRouteSource);
	for (const [route, module] of routeModules) {
		const wrapper =
			route === '/'
				? join(project, 'app', 'index.tsx')
				: routeFile(project, route);
		files.set(wrapper, nativeWrapperSource(wrapper, module));
	}
	const changes = await Promise.all(
		[...files].map(([path, source]) => writeManagedFile(path, source, true))
	);
	const changed = changes.filter(Boolean).length;

	return { changed, path: project, written: [...files.keys()] };
};

const walkFiles = async (root: string, directory = root): Promise<string[]> => {
	const entries = await readdir(directory, { withFileTypes: true });
	const nested = await Promise.all(
		entries.map((entry) => {
			const path = join(directory, entry.name);
			if (entry.isDirectory()) return walkFiles(root, path);
			if (entry.isFile()) return [path];
			throw new TypeError(
				`Expo embedded bundle cannot contain a symbolic link or special file: ${path}.`
			);
		})
	);

	return nested.flat().sort();
};

const renameIfPresent = async (source: string, destination: string) => {
	try {
		await rename(source, destination);

		return true;
	} catch (error) {
		if (
			typeof error === 'object' &&
			error !== null &&
			Reflect.get(error, 'code') === 'ENOENT'
		) {
			return false;
		}
		throw error;
	}
};

const installStagedDirectory = async (staging: string, destination: string) => {
	const backup = `${destination}.previous-${crypto.randomUUID()}`;
	const moved = await renameIfPresent(destination, backup);
	try {
		await rename(staging, destination);
		if (moved) await rm(backup, { force: true, recursive: true });
	} catch (error) {
		if (moved) await rename(backup, destination);
		throw error;
	}
};

const assetModuleSource = (
	assets: { asset: string; path: string }[],
	bundleId: string
) => `${EXPO_GENERATED_HEADER}import { Asset } from 'expo-asset';
import { Directory, File, Paths } from 'expo-file-system';

declare const require: (path: string) => number;
const BUNDLE_ID = ${JSON.stringify(bundleId)};
const ASSETS = [
${assets.map(({ asset, path }) => `\t{ module: require(${JSON.stringify(asset)}), path: ${JSON.stringify(path)} }`).join(',\n')}
] as const;

export const materializeAbsoluteWebBundle = async () => {
	const root = new Directory(Paths.document, 'absolutejs-web', BUNDLE_ID);
	root.create({ idempotent: true, intermediates: true });
	for (const entry of ASSETS) {
		const parts = entry.path.split('/');
		const name = parts.pop();
		if (!name) throw new Error('AbsoluteJS embedded asset path is invalid.');
		const directory = new Directory(root, ...parts);
		directory.create({ idempotent: true, intermediates: true });
		const destination = new File(directory, name);
		if (destination.exists) continue;
		const asset = await Asset.fromModule(entry.module).downloadAsync();
		if (!asset.localUri) throw new Error('Expo did not materialize an embedded AbsoluteJS asset.');
		new File(asset.localUri).copy(destination);
	}

	return new File(root, 'index.html').uri;
};
`;

export const syncAbsoluteExpoWebAssets = async (
	config: NormalizedAbsoluteMobileConfig
) => {
	if (config.engine !== 'expo')
		throw new TypeError('Expo asset sync requires mobile.engine: expo.');
	const marker = join(config.nativeProjectDirectory, EXPO_PROJECT_MARKER);
	if (!(await exists(marker))) {
		throw new TypeError(
			'Expo asset sync requires an AbsoluteJS-managed Expo project. Run mobile init first.'
		);
	}
	const manifestPath = join(
		config.bundleDirectory,
		'absolute-mobile-manifest.json'
	);
	const manifest: unknown = JSON.parse(await readFile(manifestPath, 'utf8'));
	const appBuild =
		typeof manifest === 'object' &&
		manifest !== null &&
		typeof Reflect.get(manifest, 'appBuild') === 'string'
			? String(Reflect.get(manifest, 'appBuild'))
			: undefined;
	if (!appBuild)
		throw new TypeError('AbsoluteJS mobile manifest has no appBuild.');
	const files = await walkFiles(config.bundleDirectory);
	const bundleHash = createHash('sha256');
	const filesWithContents = await Promise.all(
		files.map(async (file) => ({ contents: await readFile(file), file }))
	);
	filesWithContents.forEach(({ contents, file }) => {
		bundleHash.update(
			relative(config.bundleDirectory, file).replaceAll('\\', '/')
		);
		bundleHash.update('\0');
		bundleHash.update(contents);
		bundleHash.update('\0');
	});
	const bundleId = `amexpo_${bundleHash.digest('hex')}`;
	const destination = join(
		config.nativeProjectDirectory,
		'assets',
		'absolute'
	);
	await mkdir(dirname(destination), { recursive: true });
	const staging = await mkdtemp(
		join(dirname(destination), `.${basename(destination)}.stage-`)
	);
	let assets: { asset: string; path: string }[];
	try {
		assets = await Promise.all(
			files.map(async (source, index) => {
				const name = `${String(index).padStart(6, '0')}${EXPO_ASSET_EXTENSION}`;
				await cp(source, join(staging, name));

				return {
					asset: portableRelative(
						join(config.nativeProjectDirectory, 'src', 'generated'),
						join(destination, name)
					),
					path: relative(config.bundleDirectory, source).replaceAll(
						'\\',
						'/'
					)
				};
			})
		);
		await installStagedDirectory(staging, destination);
	} catch (error) {
		await rm(staging, { force: true, recursive: true });
		throw error;
	}
	const generated = join(
		config.nativeProjectDirectory,
		'src',
		'generated',
		'webAssets.ts'
	);
	await writeManagedFile(
		generated,
		assetModuleSource(assets, bundleId),
		true
	);

	return { appBuild, assets: assets.length, bundleId, path: destination };
};
