import { join } from 'node:path';

const HEADER =
	'// Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync.\n';
const XML_HEADER =
	'<!-- Generated by AbsoluteJS. Edit absolute.config.ts, then run absolute mobile sync. -->\n';

const moduleConfig = `${JSON.stringify(
	{
		android: {
			modules: [
				'expo.modules.absolutemobileobservability.AbsoluteMobileObservabilityModule'
			]
		},
		apple: { modules: ['AbsoluteMobileObservabilityModule'] },
		platforms: ['apple', 'android']
	},
	null,
	2
)}
`;

const podspec = `${HEADER}Pod::Spec.new do |s|
  s.name = 'AbsoluteMobileObservability'
  s.version = '0.0.1'
  s.summary = 'AbsoluteJS provider-neutral native process diagnostics'
  s.description = 'Generated MetricKit bridge for an AbsoluteJS Expo application.'
  s.author = 'AbsoluteJS'
  s.homepage = 'https://absolutejs.com'
  s.platforms = { :ios => '16.4' }
  s.source = { git: '' }
  s.static_framework = true
  s.dependency 'ExpoModulesCore'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.source_files = '**/*.{h,m,mm,swift,hpp,cpp}'
end
`;

const iosModule = `${HEADER}import ExpoModulesCore
import MetricKit

public final class AbsoluteMobileObservabilityModule: Module, MXMetricManagerSubscriber {
  private static let maximumReports = 8
  private static let maximumReportBytes = 64 * 1024
  private static let queue = DispatchQueue(label: "dev.absolute.expo-mobile-observability")

  public func definition() -> ModuleDefinition {
    Name("AbsoluteMobileObservability")

    OnCreate { MXMetricManager.shared.add(self) }
    OnDestroy { MXMetricManager.shared.remove(self) }

    AsyncFunction("pending") { () -> [String: Any] in
      Self.queue.sync {
        let reports: [[String: Any]] = Self.files().compactMap { file in
          guard let data = try? Data(contentsOf: file),
                let value = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return nil }
          return value
        }
        return ["reports": reports]
      }
    }

    AsyncFunction("acknowledge") { (options: [String: Any]) in
      let accepted = Set(options["ids"] as? [String] ?? [])
      Self.queue.sync {
        for file in Self.files() {
          guard let data = try? Data(contentsOf: file),
                let value = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                let id = value["id"] as? String,
                accepted.contains(id) else { continue }
          try? FileManager.default.removeItem(at: file)
        }
      }
    }
  }

  private static func root() -> URL? {
    guard let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first else { return nil }
    let root = support.appendingPathComponent("AbsoluteMobileObservability", isDirectory: true)
    try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    return root
  }

  private static func files() -> [URL] {
    guard let root = root() else { return [] }
    return ((try? FileManager.default.contentsOfDirectory(at: root, includingPropertiesForKeys: nil)) ?? [])
      .filter { $0.pathExtension == "json" }
      .sorted { $0.lastPathComponent < $1.lastPathComponent }
  }

  private static func enqueue(kind: String, occurredAt: Double, details: [AnyHashable: Any]) {
    guard let root = root() else { return }
    let id = UUID().uuidString.lowercased()
    var report: [String: Any] = [
      "details": Dictionary(uniqueKeysWithValues: details.map { (String(describing: $0.key), $0.value) }),
      "id": id,
      "kind": kind,
      "occurredAt": occurredAt,
      "platform": "ios"
    ]
    guard JSONSerialization.isValidJSONObject(report),
          let original = try? JSONSerialization.data(withJSONObject: report) else { return }
    if original.count > maximumReportBytes {
      report["details"] = [
        "diagnosticPrefix": String(decoding: original.prefix(24 * 1024), as: UTF8.self),
        "originalBytes": original.count,
        "truncated": true
      ]
    }
    guard let data = try? JSONSerialization.data(withJSONObject: report),
          data.count <= maximumReportBytes else { return }
    let timestamp = String(format: "%013.0f", occurredAt)
    try? data.write(to: root.appendingPathComponent("\\(timestamp)-\\(id).json"), options: .atomic)
    let overflow = max(0, files().count - maximumReports)
    for file in files().prefix(overflow) { try? FileManager.default.removeItem(at: file) }
  }

  public func didReceive(_ payloads: [MXDiagnosticPayload]) {
    Self.queue.async {
      for payload in payloads {
        let at = payload.timeStampEnd.timeIntervalSince1970 * 1000
        for value in payload.crashDiagnostics ?? [] { Self.enqueue(kind: "crash", occurredAt: at, details: value.dictionaryRepresentation()) }
        for value in payload.hangDiagnostics ?? [] { Self.enqueue(kind: "hang", occurredAt: at, details: value.dictionaryRepresentation()) }
        for value in payload.cpuExceptionDiagnostics ?? [] { Self.enqueue(kind: "cpu-exception", occurredAt: at, details: value.dictionaryRepresentation()) }
        for value in payload.diskWriteExceptionDiagnostics ?? [] { Self.enqueue(kind: "disk-write-exception", occurredAt: at, details: value.dictionaryRepresentation()) }
        if #available(iOS 16.0, *) {
          for value in payload.appLaunchDiagnostics ?? [] { Self.enqueue(kind: "app-launch", occurredAt: at, details: value.dictionaryRepresentation()) }
        }
      }
    }
  }
}
`;

const androidBuild = `${HEADER}plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.absolutemobileobservability'
version = '0.0.1'

android {
  namespace 'expo.modules.absolutemobileobservability'
  defaultConfig {
    versionCode 1
    versionName '0.0.1'
  }
  lintOptions { abortOnError false }
}
`;

const androidManifest = `${XML_HEADER}<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
`;

const androidModule = `${HEADER}package expo.modules.absolutemobileobservability

import android.app.ActivityManager
import android.app.ApplicationExitInfo
import android.content.pm.ApplicationInfo
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Base64
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStream
import java.nio.charset.StandardCharsets
import java.util.UUID
import org.json.JSONArray
import org.json.JSONObject

class AbsoluteMobileObservabilityModule : Module() {
  companion object {
    private const val MAX_REPORTS = 8
    private const val MAX_TRACE_BYTES = 32 * 1024
    private const val ACKNOWLEDGED_KEY = "acknowledged"
    private const val CRASH_TEST_KEY = "crash-test-id"
    private const val PREFERENCES = "AbsoluteMobileObservability"
  }

  override fun definition() = ModuleDefinition {
    Name("AbsoluteMobileObservability")

    AsyncFunction("pending") {
      collect()
      mapOf("reports" to files().mapNotNull { readReport(it) })
    }

    AsyncFunction("acknowledge") { options: Map<String, List<String>> ->
      val accepted = options["ids"]?.toSet() ?: emptySet()
      val acknowledged = acknowledged().toMutableSet()
      files().forEach { file ->
        val report = readReport(file)
        val id = report?.get("id") as? String
        if (id != null && accepted.contains(id)) {
          acknowledged.add(id)
          file.delete()
        }
      }
      writeAcknowledged(acknowledged)
    }

    AsyncFunction("crashForTesting") { options: Map<String, String> ->
      val context = context() ?: return@AsyncFunction false
      if (context.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE == 0) {
        throw IllegalStateException("Native observability crash injection requires a debuggable build.")
      }
      val testId = options["testId"]
        ?.takeIf { it.matches(Regex("[A-Za-z0-9._:-]{1,128}")) }
        ?: throw IllegalArgumentException("Native observability crash injection requires a valid testId.")
      val preferences = context.getSharedPreferences(PREFERENCES, 0)
      if (preferences.getString(CRASH_TEST_KEY, null) == testId) {
        return@AsyncFunction false
      }
      preferences.edit().putString(CRASH_TEST_KEY, testId).commit()
      Handler(Looper.getMainLooper()).post {
        throw RuntimeException("AbsoluteJS native observability acceptance crash: $testId")
      }
      true
    }
  }

  private fun context() = appContext.reactContext

  private fun root(): File? {
    val context = context() ?: return null
    return File(context.filesDir, "absolute-mobile-observability").also { it.mkdirs() }
  }

  private fun files(): List<File> = root()?.listFiles { _, name -> name.endsWith(".json") }
    ?.sortedBy { it.name } ?: emptyList()

  private fun acknowledged(): Set<String> {
    val context = context() ?: return emptySet()
    return try {
      val values = JSONArray(context.getSharedPreferences(PREFERENCES, 0).getString(ACKNOWLEDGED_KEY, "[]"))
      (0 until values.length()).map { values.optString(it) }.toSet()
    } catch (_: Exception) { emptySet() }
  }

  private fun writeAcknowledged(values: Set<String>) {
    val context = context() ?: return
    val bounded = values.sorted().takeLast(64)
    context.getSharedPreferences(PREFERENCES, 0).edit()
      .putString(ACKNOWLEDGED_KEY, JSONArray(bounded).toString()).apply()
  }

  private fun kind(reason: Int): String? = when (reason) {
    ApplicationExitInfo.REASON_ANR -> "anr"
    ApplicationExitInfo.REASON_CRASH -> "crash"
    ApplicationExitInfo.REASON_CRASH_NATIVE -> "native-crash"
    ApplicationExitInfo.REASON_LOW_MEMORY -> "low-memory"
    ApplicationExitInfo.REASON_EXCESSIVE_RESOURCE_USAGE -> "resource-exhaustion"
    ApplicationExitInfo.REASON_INITIALIZATION_FAILURE -> "initialization-failure"
    ApplicationExitInfo.REASON_SIGNALED -> "signal"
    else -> null
  }

  private fun trace(info: ApplicationExitInfo): ByteArray? = try {
    info.traceInputStream?.use { input ->
      val output = ByteArrayOutputStream()
      val buffer = ByteArray(4096)
      var total = 0
      while (true) {
        val count = input.read(buffer, 0, minOf(buffer.size, MAX_TRACE_BYTES + 1 - total))
        if (count <= 0) break
        output.write(buffer, 0, count)
        total += count
        if (total > MAX_TRACE_BYTES) return null
      }
      output.toByteArray()
    }
  } catch (_: Exception) { null }

  private fun report(info: ApplicationExitInfo): JSONObject? {
    val kind = kind(info.reason) ?: return null
    val id = "android:" + info.timestamp + ":" + info.reason + ":" + info.status
    return try {
      val details = JSONObject()
        .put("importance", info.importance)
        .put("pssKb", info.pss)
        .put("reason", info.reason)
        .put("rssKb", info.rss)
        .put("status", info.status)
      info.description?.let { details.put("description", it) }
      trace(info)?.takeIf { it.isNotEmpty() }?.let { trace ->
        if (info.reason == ApplicationExitInfo.REASON_CRASH_NATIVE) {
          details.put("trace", Base64.encodeToString(trace, Base64.NO_WRAP))
          details.put("traceEncoding", "android-tombstone-protobuf-base64")
        } else {
          details.put("trace", String(trace, StandardCharsets.UTF_8))
          details.put("traceEncoding", "utf-8")
        }
      }
      JSONObject().put("details", details).put("id", id).put("kind", kind)
        .put("occurredAt", info.timestamp).put("platform", "android")
    } catch (_: Exception) { null }
  }

  private fun collect() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) return
    val context = context() ?: return
    val directory = root() ?: return
    val manager = context.getSystemService(ActivityManager::class.java) ?: return
    val ignored = (acknowledged() + files().mapNotNull { readReport(it)?.get("id") as? String }).toMutableSet()
    manager.getHistoricalProcessExitReasons(null, 0, 16).forEach { exit ->
      val report = report(exit) ?: return@forEach
      val id = report.optString("id")
      if (ignored.contains(id)) return@forEach
      val target = File(directory, String.format(java.util.Locale.ROOT, "%013d-%s.json", exit.timestamp, UUID.randomUUID()))
      try {
        FileOutputStream(target).use { it.write(report.toString().toByteArray(StandardCharsets.UTF_8)) }
        ignored.add(id)
      } catch (_: Exception) {}
    }
    files().dropLast(MAX_REPORTS).forEach { it.delete() }
  }

  private fun read(input: InputStream): ByteArray {
    val output = ByteArrayOutputStream()
    val buffer = ByteArray(4096)
    while (true) {
      val count = input.read(buffer)
      if (count < 0) break
      output.write(buffer, 0, count)
    }
    return output.toByteArray()
  }

  private fun readReport(file: File): Map<String, Any?>? = try {
    FileInputStream(file).use { JSONObject(String(read(it), StandardCharsets.UTF_8)).toMap() }
  } catch (_: Exception) { null }

  private fun JSONObject.toMap(): Map<String, Any?> = keys().asSequence().associateWith { key ->
    when (val value = get(key)) {
      is JSONObject -> value.toMap()
      is JSONArray -> (0 until value.length()).map { index ->
        when (val item = value.get(index)) {
          is JSONObject -> item.toMap()
          else -> item
        }
      }
      JSONObject.NULL -> null
      else -> value
    }
  }
}
`;

export const expoNativeObservabilityRuntimeSource = `${HEADER}import { requireNativeModule } from 'expo';
import { AppState, Platform } from 'react-native';
import { ABSOLUTE_MOBILE_MANIFEST } from './webAssets';

type NativeObservabilityModule = {
	acknowledge(options: { ids: string[] }): Promise<void>;
	crashForTesting(options: { testId: string }): Promise<boolean>;
	pending(): Promise<{ reports: unknown[] }>;
};
type NativeReport = { details: Record<string, unknown>; id: string; kind: string; occurredAt: number; platform: 'android' | 'ios' };
const native = requireNativeModule<NativeObservabilityModule>('AbsoluteMobileObservability');
const KINDS = new Set(['anr', 'app-launch', 'cpu-exception', 'crash', 'disk-write-exception', 'hang', 'initialization-failure', 'low-memory', 'native-crash', 'resource-exhaustion', 'signal']);
const ID = /^[A-Za-z0-9._:-]{1,128}$/;
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const redactText = (value: string) => value.slice(0, 8192)
	.replace(/\\b(Bearer)\\s+[A-Za-z0-9._~+/-]+=*/gi, '$1 [REDACTED]')
	.replace(/([?&](?:access_token|api_?key|authorization|code|id_token|password|refresh_token|secret|token)=)[^&#\\s]*/gi, '$1[REDACTED]')
	.replace(/\\b((?:access_?token|api_?key|authorization|client_?secret|cookie|id_?token|password|passwd|refresh_?token|secret|token)\\s*[:=]\\s*)[^,\\s;]+/gi, '$1[REDACTED]')
	.replace(/\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b/g, '[REDACTED]');
const redact = (value: unknown, depth = 0): unknown => {
	if (depth >= 8) return '[TRUNCATED]';
	if (typeof value === 'string') return redactText(value);
	if (value === null || typeof value === 'number' || typeof value === 'boolean') return value;
	if (Array.isArray(value)) return value.slice(0, 64).map(entry => redact(entry, depth + 1));
	if (!isRecord(value)) return String(value).slice(0, 8192);
	return Object.fromEntries(Object.entries(value).slice(0, 128).map(([key, entry]) => [key, /(?:authorization|cookie|password|secret|token)/i.test(key) ? '[REDACTED]' : redact(entry, depth + 1)]));
};
const parse = (value: unknown): NativeReport | undefined => {
	if (!isRecord(value) || !isRecord(value.details) || typeof value.id !== 'string' || !ID.test(value.id) || typeof value.kind !== 'string' || !KINDS.has(value.kind) || typeof value.occurredAt !== 'number' || !Number.isFinite(value.occurredAt) || value.occurredAt <= 0 || value.platform !== 'android' && value.platform !== 'ios') return;
	const details = redact(value.details);
	if (!isRecord(details) || new TextEncoder().encode(JSON.stringify(details)).byteLength > 64 * 1024) return;
	return { details, id: value.id, kind: value.kind, occurredAt: value.occurredAt, platform: value.platform };
};
const sampled = (id: string, rate: number) => {
	if (rate >= 1) return true;
	let hash = 2166136261;
	for (const character of id) { hash ^= character.codePointAt(0) ?? 0; hash = Math.imul(hash, 16777619); }
	return (hash >>> 0) / 4294967296 < rate;
};
let drainPromise: Promise<void> | undefined;
let started = false;
const drain = () => {
	drainPromise ??= (async () => {
		const manifest = ABSOLUTE_MOBILE_MANIFEST;
		const config = manifest?.observability;
		if (!manifest || !config || Platform.OS !== 'android' && Platform.OS !== 'ios') return;
		const reports = (await native.pending()).reports.slice(0, 8).map(parse).filter((report): report is NativeReport => report !== undefined);
		const discarded = reports.filter(report => !sampled(report.id, config.sampleRate));
		if (discarded.length) await native.acknowledge({ ids: discarded.map(report => report.id) });
		const selected = reports.filter(report => sampled(report.id, config.sampleRate));
		if (!selected.length) return;
		const response = await fetch(config.endpoint, {
			body: JSON.stringify({ ...(config.environment ? { environment: config.environment } : {}), events: selected.map(report => ({ at: report.occurredAt, extra: { nativeDiagnostic: report.details, nativeDiagnosticId: report.id }, groupingKey: 'absolute-native:' + report.platform + ':' + report.kind, level: ['app-launch', 'cpu-exception', 'disk-write-exception', 'low-memory', 'resource-exhaustion', 'signal'].includes(report.kind) ? 'warning' : 'error', message: 'Native process diagnostic — ' + report.kind, name: 'AbsoluteMobileNativeDiagnostic', tags: { absoluteMobile: 'true', mobileAppBuild: manifest.appBuild, mobileEngine: 'expo', mobileFailurePhase: 'native-process', mobileManifestFormat: '1', mobileNativeRuntime: 'expo', mobilePlatform: report.platform, mobileRuntime: manifest.runtime } })), project: config.project, release: manifest.appBuild, v: 1 }),
			headers: { 'content-type': 'application/json' },
			method: 'POST'
		});
		if (response.ok) await native.acknowledge({ ids: selected.map(report => report.id) });
	})().catch(() => undefined).finally(() => { drainPromise = undefined; });
	return drainPromise;
};
export const startAbsoluteExpoNativeObservability = () => {
	if (!started) {
		started = true;
		AppState.addEventListener('change', state => { if (state === 'active') void drain(); });
	}
	return drain();
};
export const crashAbsoluteExpoNativeObservabilityForTesting = (testId: string) => native.crashForTesting({ testId });
`;

export const absoluteExpoNativeObservabilityFiles = (project: string) =>
	new Map<string, string>([
		[
			join(
				project,
				'modules/absolute-mobile-observability/expo-module.config.json'
			),
			moduleConfig
		],
		[
			join(
				project,
				'modules/absolute-mobile-observability/ios/AbsoluteMobileObservability.podspec'
			),
			podspec
		],
		[
			join(
				project,
				'modules/absolute-mobile-observability/ios/AbsoluteMobileObservabilityModule.swift'
			),
			iosModule
		],
		[
			join(
				project,
				'modules/absolute-mobile-observability/android/build.gradle'
			),
			androidBuild
		],
		[
			join(
				project,
				'modules/absolute-mobile-observability/android/src/main/AndroidManifest.xml'
			),
			androidManifest
		],
		[
			join(
				project,
				'modules/absolute-mobile-observability/android/src/main/java/expo/modules/absolutemobileobservability/AbsoluteMobileObservabilityModule.kt'
			),
			androidModule
		],
		[
			join(project, 'src/generated/AbsoluteNativeObservability.ts'),
			expoNativeObservabilityRuntimeSource
		]
	]);

export const absoluteExpoNativeObservabilityPaths = (project: string) => [
	...absoluteExpoNativeObservabilityFiles(project).keys()
];
