import { describe, expect, test, afterAll, afterEach } from 'bun:test';
import { resolve } from 'node:path';
import { startDevServer, type DevServer } from '../../../helpers/devServer';
import { connectHMR, type HMRClient } from '../../../helpers/ws';
import { mutateFile, restoreAllFiles } from '../../../helpers/file';

const PROJECT_ROOT = resolve(import.meta.dir, '..', '..', '..', '..');

let server: DevServer;
let client: HMRClient;

afterEach(() => {
	restoreAllFiles();
});

afterAll(async () => {
	client?.close();
	await server?.kill();
});

/* Verifies the tier-0 SSR-bundle rebuild scheduled from each
 * framework's HMR fast path. Pre-fix (Angular #196 / Svelte+Vue
 * #200), surgical updates patched the running browser session
 * but the on-disk SSR bundle stayed frozen at startup-time
 * bytes, so any fresh-tab load (or curl) returned the pre-edit
 * component until the page entry itself was touched.
 *
 * The fix schedules a debounced `Bun.build` from each fast
 * path; when it completes the server broadcasts a
 * `<framework>-tier-zero-ssr-rebuild-complete` HMR message.
 * We wait on that signal and then re-fetch the page to
 * confirm SSR is serving fresh bytes. The 15s test deadline
 * is a runner-level safety net — the operation itself blocks
 * on the WebSocket event, not on time. */
const TEST_DEADLINE_MS = 15_000;

/* Drain stale broadcasts from prior tests' rebuilds (the
 * afterEach file-restore re-triggers a rebuild, whose broadcast
 * may land before the next test's mutation) so we wait on the
 * broadcast generated by *this* test's edit. */
const driveRebuild = async (
	framework: 'vue' | 'svelte' | 'angular',
	mutate: () => void,
	url: string,
	sentinel: string
) => {
	client.drain();
	mutate();
	await client.waitFor(`${framework}-tier-zero-ssr-rebuild-complete`);
	const html = await (await fetch(url)).text();
	expect(html).toContain(sentinel);
};

describe('Tier-0 SSR catches up to fresh component content', () => {
	test('setup: start server and connect', async () => {
		server = await startDevServer();
		client = await connectHMR(server.port);
		await client.waitFor('manifest');
		await client.waitFor('connected');
		client.drain();
	}, 60_000);

	test(
		'vue: SSR returns post-edit content after rebuild',
		async () => {
			const vuePage = resolve(
				PROJECT_ROOT,
				'example/vue/pages/VueExample.vue'
			);

			await driveRebuild(
				'vue',
				() =>
					mutateFile(vuePage, (c) =>
						c.replace(
							'<a href="/">AbsoluteJS</a>',
							'<a href="/">AbsoluteJS SSR_TIER0_VUE</a>'
						)
					),
				`${server.baseUrl}/vue`,
				'SSR_TIER0_VUE'
			);
		},
		TEST_DEADLINE_MS
	);

	test(
		'svelte: SSR returns post-edit content after rebuild',
		async () => {
			const sveltePage = resolve(
				PROJECT_ROOT,
				'example/svelte/pages/SvelteExample.svelte'
			);

			await driveRebuild(
				'svelte',
				() =>
					mutateFile(sveltePage, (c) =>
						c.replace(
							'<a href="/">AbsoluteJS</a>',
							'<a href="/">AbsoluteJS SSR_TIER0_SVELTE</a>'
						)
					),
				`${server.baseUrl}/svelte`,
				'SSR_TIER0_SVELTE'
			);
		},
		TEST_DEADLINE_MS
	);

	test(
		'angular: SSR returns post-edit content after rebuild',
		async () => {
			const angularTemplate = resolve(
				PROJECT_ROOT,
				'example/angular/templates/angular-example.html'
			);

			await driveRebuild(
				'angular',
				() =>
					mutateFile(angularTemplate, (c) =>
						c.replace(
							'<a href="/">AbsoluteJS</a>',
							'<a href="/">AbsoluteJS SSR_TIER0_NG</a>'
						)
					),
				`${server.baseUrl}/angular`,
				'SSR_TIER0_NG'
			);
		},
		TEST_DEADLINE_MS
	);
});
