/* SQL Server over the `mssql` (tedious) driver, an optional peer dependency
   loaded only when the URL is sqlserver:// or mssql://. */
import type {
	DbColumnMeta,
	DbConnection,
	DbRow,
	DbTableMeta,
	MssqlColumnRow,
	MssqlTarget
} from '../../../../types/db';
import {
	chunkRows,
	insertableColumns,
	mssqlUpsert,
	quoteMssqlIdent,
	rowsPerChunk
} from './sqlText';
import { encodeMssqlValue, normalizeRow } from './values';

// SQL Server allows 2100 parameters per request; keep headroom.
const MSSQL_PARAM_LIMIT = 2000;
const DEFAULT_PORT = 1433;
const UNICODE_BYTES = 2;
// sys.columns.max_length for (n)varchar(max) / varbinary(max).
const MAX_LENGTH_UNBOUNDED = -1;
const LENGTH_TYPES = ['binary', 'char', 'varbinary', 'varchar'];
const UNICODE_LENGTH_TYPES = ['nchar', 'nvarchar'];
const SCALE_TYPES = ['datetime2', 'datetimeoffset', 'time'];
const DECIMAL_TYPES = ['decimal', 'numeric'];
/* Read back through CONVERT style 126 (ISO 8601, full precision) so the
   restore can cast the text straight back without a JS Date in between. */
const TEMPORAL_TYPES = [
	'date',
	'datetime',
	'datetime2',
	'datetimeoffset',
	'smalldatetime',
	'time'
];
const MONEY_TYPES = ['money', 'smallmoney'];
const CLR_TYPES = ['geography', 'geometry', 'hierarchyid'];
const BINARY_TYPES = ['binary', 'image', 'varbinary', ...CLR_TYPES];
// rowversion/timestamp values are generated by the server.
const SERVER_GENERATED_TYPES = ['timestamp'];

const truthy = (value: string | undefined) =>
	value !== undefined && ['1', 'true', 'yes'].includes(value.toLowerCase());

const optionalValue = (value: string | undefined) =>
	value === undefined || value === '' ? undefined : value;

/* `sqlserver://host[\instance][:port];database=x;user=u;password=p;…` (the
   Prisma / JDBC form) or `mssql://user:pass@host:port/db?encrypt=…`. */
export const mssqlColumnType = (row: MssqlColumnRow) => {
	const type = row.type.toLowerCase();
	const maxOr = (length: number) =>
		row.max_length === MAX_LENGTH_UNBOUNDED ? 'max' : String(length);
	if (LENGTH_TYPES.includes(type)) return `${type}(${maxOr(row.max_length)})`;
	if (UNICODE_LENGTH_TYPES.includes(type))
		return `${type}(${maxOr(row.max_length / UNICODE_BYTES)})`;
	if (DECIMAL_TYPES.includes(type))
		return `${type}(${row.precision}, ${row.scale})`;
	if (SCALE_TYPES.includes(type)) return `${type}(${row.scale})`;

	return type;
};
export const parseMssqlUrl = (url: string) => {
	if (/^sqlserver:/i.test(url)) {
		const [hostPart = '', ...pairs] = url
			.replace(/^sqlserver:\/\//i, '')
			.split(';');
		const settings = new Map(
			pairs
				.filter((pair) => pair.includes('='))
				.map((pair) => {
					const [key = '', ...rest] = pair.split('=');

					return [key.trim().toLowerCase(), rest.join('=').trim()];
				})
		);
		const [hostWithInstance = '', port] = hostPart.split(':');
		const [server = '', instanceName] = hostWithInstance.split('\\');
		const target: MssqlTarget = {
			database: optionalValue(
				settings.get('database') ?? settings.get('initial catalog')
			),
			encrypt: settings.has('encrypt')
				? truthy(settings.get('encrypt'))
				: true,
			instanceName: optionalValue(instanceName),
			password: settings.get('password') ?? settings.get('pwd'),
			port: port === undefined ? undefined : Number(port),
			server,
			trustServerCertificate: truthy(
				settings.get('trustservercertificate')
			),
			user:
				settings.get('user') ??
				settings.get('username') ??
				settings.get('user id') ??
				settings.get('uid')
		};

		return target;
	}
	const parsed = new URL(url);
	const params = parsed.searchParams;
	const target: MssqlTarget = {
		database: optionalValue(decodeURIComponent(parsed.pathname.slice(1))),
		encrypt: params.has('encrypt')
			? truthy(params.get('encrypt') ?? undefined)
			: true,
		instanceName: optionalValue(params.get('instanceName') ?? undefined),
		password: optionalValue(decodeURIComponent(parsed.password)),
		port: parsed.port === '' ? undefined : Number(parsed.port),
		server: parsed.hostname,
		trustServerCertificate: truthy(
			params.get('trustServerCertificate') ?? undefined
		),
		user: optionalValue(decodeURIComponent(parsed.username))
	};

	return target;
};

const toColumn = (row: MssqlColumnRow) => {
	const type = row.type.toLowerCase();
	const column: DbColumnMeta = {
		generated: row.is_computed || SERVER_GENERATED_TYPES.includes(type),
		identity: row.is_identity,
		isJson: false,
		kind: 'other',
		name: row.name,
		sqlType: mssqlColumnType(row)
	};
	if (BINARY_TYPES.includes(type)) column.kind = 'binary';
	if (TEMPORAL_TYPES.includes(type)) column.kind = 'temporal';

	return column;
};

const selectExpression = (col: DbColumnMeta) => {
	const name = quoteMssqlIdent(col.name);
	const type = (col.sqlType ?? '').replace(/\(.*$/, '');
	if (TEMPORAL_TYPES.includes(type))
		return `convert(nvarchar(max), ${name}, 126) as ${name}`;
	if (MONEY_TYPES.includes(type))
		return `convert(nvarchar(max), ${name}, 2) as ${name}`;
	if (DECIMAL_TYPES.includes(type))
		return `cast(${name} as nvarchar(max)) as ${name}`;
	if (CLR_TYPES.includes(type))
		return `cast(${name} as varbinary(max)) as ${name}`;

	return name;
};

const loadMssql = async () => {
	try {
		return await import('mssql');
	} catch {
		throw new Error(
			'SQL Server support needs the optional mssql driver in this project: bun add mssql'
		);
	}
};

export const openMssql = async (url: string) => {
	const { ConnectionPool } = await loadMssql();
	const target = parseMssqlUrl(url);
	const pool = new ConnectionPool({
		database: target.database,
		options: {
			encrypt: target.encrypt,
			instanceName: target.instanceName,
			trustServerCertificate: target.trustServerCertificate
		},
		password: target.password,
		port:
			target.instanceName === undefined
				? (target.port ?? DEFAULT_PORT)
				: target.port,
		server: target.server,
		user: target.user
	});
	await pool.connect();

	const query = async (text: string, params: unknown[] = []) => {
		const request = pool.request();
		params.forEach((value, idx) => request.input(`p${idx}`, value));
		const result = await request.query<DbRow>(text);

		return result.recordset ?? [];
	};

	const [schemaRow] = await query('select schema_name() as name');
	const schema = String(schemaRow?.name ?? 'dbo');
	const qualified = (name: string) =>
		`${quoteMssqlIdent(schema)}.${quoteMssqlIdent(name)}`;

	const listTables = async () => {
		const rows = await query(
			'select name from sys.tables where schema_id = schema_id(@p0) and is_ms_shipped = 0 order by name',
			[schema]
		);

		return rows.map((row) => String(row.name));
	};

	const tableMeta = async (name: string) => {
		const [columnRows, keyRows] = await Promise.all([
			query(
				'select c.name, type_name(c.system_type_id) as type, c.max_length, c.precision, c.scale, c.is_computed, c.is_identity from sys.columns c where c.object_id = object_id(@p0) order by c.column_id',
				[qualified(name)]
			),
			query(
				'select c.name from sys.indexes i join sys.index_columns ic on ic.object_id = i.object_id and ic.index_id = i.index_id join sys.columns c on c.object_id = ic.object_id and c.column_id = ic.column_id where i.is_primary_key = 1 and i.object_id = object_id(@p0) order by ic.key_ordinal',
				[qualified(name)]
			)
		]);
		const columns = columnRows.map((row) => {
			const column: MssqlColumnRow = {
				is_computed: row.is_computed === true,
				is_identity: row.is_identity === true,
				max_length: Number(row.max_length),
				name: String(row.name),
				precision: Number(row.precision),
				scale: Number(row.scale),
				type: String(row.type)
			};

			return toColumn(column);
		});
		const primaryKey = keyRows.map((row) => String(row.name));
		const meta: DbTableMeta = { columns, name, primaryKey };

		return meta;
	};

	const foreignLinks = async () => {
		const rows = await query(
			'select object_name(fk.parent_object_id) as child, object_name(fk.referenced_object_id) as parent from sys.foreign_keys fk where fk.schema_id = schema_id(@p0)',
			[schema]
		);

		return rows.map((row) => ({
			from: String(row.child),
			to: String(row.parent)
		}));
	};

	const readRows = async (meta: DbTableMeta) => {
		const list = meta.columns.map(selectExpression).join(', ');
		const rows = await query(`select ${list} from ${qualified(meta.name)}`);

		return rows.map(normalizeRow);
	};

	const insertChunk = async (meta: DbTableMeta, rows: DbRow[]) => {
		const cols = insertableColumns(meta);
		const params = rows.flatMap((row) =>
			cols.map((col) => encodeMssqlValue(col, row[col.name]))
		);
		// One request is one batch on one connection, so IDENTITY_INSERT
		// is scoped to exactly this statement.
		await query(
			mssqlUpsert(meta, rows.length, qualified(meta.name)),
			params
		);
	};

	const insertRows = async (meta: DbTableMeta, rows: DbRow[]) => {
		const size = rowsPerChunk(
			insertableColumns(meta).length,
			MSSQL_PARAM_LIMIT
		);
		await chunkRows(rows, size).reduce(async (prev, part) => {
			await prev;

			return insertChunk(meta, part);
		}, Promise.resolve());
	};

	/* TRUNCATE is refused on referenced tables, so constraints are disabled,
	   rows deleted, and constraints re-enabled WITH CHECK in one batch. */
	const truncate = async (names: string[]) => {
		if (names.length === 0) return;
		const tables = names.map(qualified);
		const statements = [
			...tables.map(
				(table) => `alter table ${table} nocheck constraint all;`
			),
			...tables.map((table) => `delete from ${table};`),
			...tables.map(
				(table) =>
					`alter table ${table} with check check constraint all;`
			)
		];
		await query(statements.join(' '));
	};

	const connection: DbConnection = {
		engine: 'mssql',
		foreignLinks,
		insertRows,
		listTables,
		readRows,
		tableMeta,
		truncate,
		afterRestore: () => Promise.resolve(),
		close: () => pool.close()
	};

	return connection;
};
